import assert from "node:assert/strict";import test from "node:test";import { readFile } from "node:fs/promises";import { join } from "node:path";
import { keccak256, recoverTransactionAddress, serializeTransaction, type Hex } from "viem";
import { circleExternalHeader,circleExternalTransaction } from "../../src/circle-v2-evm/external-proof.js";
const order=0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141n;
async function actual(){return JSON.parse(await readFile(join(process.cwd(),"tests/fixtures/circle-external/actual-monad-external-receipt.json"),"utf8"));}
async function malleated(t:Record<string,string>,s:bigint,v:bigint){const raw=serializeTransaction({type:"legacy",chainId:Number(BigInt(t.chainId!)),nonce:Number(BigInt(t.nonce!)),gas:BigInt(t.gas!),gasPrice:BigInt(t.gasPrice!),to:t.to as Hex,value:BigInt(t.value!),data:t.input as Hex},{r:t.r as Hex,s:`0x${s.toString(16).padStart(64,"0")}`,v});return{...t,s:`0x${s.toString(16).padStart(64,"0")}`,v:`0x${v.toString(16)}`,hash:keccak256(raw),from:await recoverTransactionAddress({serializedTransaction:raw})};}
test("actual canonical Monad legacy transaction and RLP block remain accepted",async()=>{const x=await actual(),t=x.eth_getTransactionByHash.result;assert.equal(t.v,"0x142");const p=await circleExternalTransaction(t);assert.equal(p.hash,"0xa960a09b6abb91ab9cc8c847d5846266cb84b83d617e162b052c60640a28a961");assert.equal(p.caller.toLowerCase(),"0x99f5a2e5d81f22ddb130f4a194584532a3dc3c2e");assert.equal(circleExternalHeader(x.block.result),x.block.result.hash);});
test("production external parser refuses high-s even when pinned viem serializes/recover same owner",async()=>{const x=await actual(),t=x.eth_getTransactionByHash.result,bad=await malleated(t,order-BigInt(t.s),BigInt(t.v)===322n?321n:322n);assert.equal(bad.from.toLowerCase(),t.from.toLowerCase());await assert.rejects(circleExternalTransaction(bad),/signature_noncanonical/);});
test("production external parser refuses foreign-chain legacy v despite self-consistent recovered caller/hash",async()=>{const x=await actual(),t=x.eth_getTransactionByHash.result,bad=await malleated(t,BigInt(t.s),37n);await assert.rejects(circleExternalTransaction(bad),/signature_chain_parity/);});
for(const [field,value] of [["r",0n],["r",order],["s",0n],["s",order/2n+1n]] as const)test(`external parser rejects ${field} range ${value===0n?"zero":"upper"}`,async()=>{const x=await actual();await assert.rejects(circleExternalTransaction({...x.eth_getTransactionByHash.result,[field]:`0x${value.toString(16).padStart(64,"0")}`}),/signature_noncanonical/);});
test("external parser refuses unprotected legacy and illegal typed parity",async()=>{const x=await actual(),t=x.eth_getTransactionByHash.result;await assert.rejects(circleExternalTransaction({...t,v:"0x1b"}),/signature_chain_parity/);await assert.rejects(circleExternalTransaction({...t,type:"0x2",v:"0x3"}),/signature_chain_parity/);});
test("canonical typed transaction authenticates only its exact protected parity and hash",async()=>{
 const {privateKeyToAccount}=await import("viem/accounts"),{parseTransaction}=await import("viem");const account=privateKeyToAccount(`0x${"09".padStart(64,"0")}`),to="0x81D40F21F12A8F0E3252Bccb954D722d4c464B64",raw=await account.signTransaction({type:"eip1559",chainId:143,nonce:3,gas:500000n,to,value:0n,data:"0x",maxFeePerGas:20000000n,maxPriorityFeePerGas:1n,accessList:[]}),p=parseTransaction(raw);
 const tx={type:"0x2",chainId:"0x8f",nonce:"0x3",gas:"0x7a120",to,value:"0x0",input:"0x",maxFeePerGas:"0x1312d00",maxPriorityFeePerGas:"0x1",accessList:[],r:p.r,s:p.s,v:`0x${p.yParity!.toString(16)}`,from:account.address,hash:keccak256(raw)};
 assert.equal((await circleExternalTransaction(tx)).hash,tx.hash);await assert.rejects(circleExternalTransaction({...tx,v:tx.v==="0x0"?"0x1":"0x0"}),/hash_or_signer/);
});
import {decodeCircleMintEvents} from "../../src/circle-v2-evm/mint-events.js";
import {decodeCircleMessage,CIRCLE_ABI,type CircleAttestation,type CircleObservation} from "../../src/circle-v2-evm/protocol.js";
import {decodeFunctionData,getAddress} from "viem";
test("shared mint helper verifies actual captured V2 net and fee transfers without accepting a missing issuer log",async()=>{
 const x=await actual(),decoded=decodeFunctionData({abi:CIRCLE_ABI,data:x.eth_getTransactionByHash.result.input}),message=decodeCircleMessage(decoded.args![0] as Hex,143,true),attested=message as CircleAttestation,feeRecipient=getAddress("0xfc1bdd1ff58200761d56ccbce73f6f42ebe56379"),input={chainId:143,receipt:x.eth_getTransactionReceipt.result} as CircleObservation;
 assert.equal(message.receivedAtomic,"40095");assert.equal(message.feeExecutedAtomic,"5");decodeCircleMintEvents(attested,input,feeRecipient);
 const receipt=structuredClone(x.eth_getTransactionReceipt.result);receipt.logs=receipt.logs.filter((l:{topics:string[];data:string})=>!(l.topics[0]!.startsWith("0xddf252")&&l.data.endsWith("0005")));assert.throws(()=>decodeCircleMintEvents(attested,{...input,receipt},feeRecipient));
 assert.throws(()=>decodeCircleMintEvents(attested,input,getAddress("0x1111111111111111111111111111111111111111")));
});
