import { mkdtemp, realpath, mkdir, writeFile, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";import { join } from "node:path";
import { decodeFunctionData, encodeFunctionResult, getAddress, keccak256, serializeTransaction, toRlp, toEventSelector, parseAbi, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { StateStore,sealWallet } from "../../src/state.js";import { canonicalJson,hashObject } from "../../src/canonical.js";
import { projectLegacyLocalProfile } from "../../src/provider-profile.js";import { evmNativeCustody } from "../../src/evm-native-custody.js";
import { AllowlistPolicyStore } from "../../src/allowlist-policy-store.js";
import { CircleUsage,circleMechanism } from "../../src/circle-v2-evm/usage.js";import { CircleRepository } from "../../src/circle-v2-evm/repository.js";
import { CircleEvmService } from "../../src/circle-v2-evm/runtime.js";import { CIRCLE_RPC_ABI } from "../../src/circle-v2-evm/rpc.js";
import { CIRCLE_DEPLOYMENT_PINS,CIRCLE_SOURCE_OWNER,CIRCLE_SOURCE_TOKEN,CIRCLE_MESSENGER,CIRCLE_MINTER,CIRCLE_TRANSMITTER,CIRCLE_RECIPIENT,circleRoute } from "../../src/circle-v2-evm/catalog.js";
import { advanceCircle,sealCircle,type CircleOperationV1 } from "../../src/circle-v2-evm/operation-model.js";
import { bindCircleAttestation,decodeCircleSource,verifyCircleApproval,encodeCircleApproval,encodeCircleBurn,encodeCircleMint,circleWord,type CircleObservation } from "../../src/circle-v2-evm/protocol.js";
import { source,event,observation,iris,message,snapshot } from "./circle-v2-evm-runtime-fixtures.js";import { initial,at } from "./circle-v2-evm-nonce-runtime-fixtures.js";
export const actor=privateKeyToAccount(`0x${"09".padStart(64,"0")}`),q=(n:bigint|number)=>`0x${BigInt(n).toString(16)}`;
export const testFeeRecipient=getAddress("0xfc1bdd1ff58200761d56ccbce73f6f42ebe56379");
const hash=(v:string)=>`0x${v.repeat(64).slice(0,64)}` as Hex,approvalHash=hash("a"),burnHash=hash("b");
function bytesQuantity(n:unknown):Hex{const x=BigInt(String(n)),s=x.toString(16);return x===0n?"0x":`0x${s.padStart(Math.ceil(s.length/2)*2,"0")}`;}
export function block(number:number,transactions:Hex[]=[],parentHash=hash("1")):Record<string,unknown>{
 const b:Record<string,unknown>={parentHash,sha3Uncles:hash("2"),miner:getAddress(`0x${"3".repeat(40)}`),stateRoot:hash("4"),transactionsRoot:hash("5"),receiptsRoot:hash("6"),logsBloom:`0x${"00".repeat(256)}`,difficulty:"0x0",number:q(number),gasLimit:"0x989680",gasUsed:"0x493e0",timestamp:q(1900000000+number),extraData:"0x",mixHash:hash("7"),nonce:`0x${"00".repeat(8)}`,baseFeePerGas:"0x1312d00",transactions};
 const fields=[...(["parentHash","sha3Uncles","miner","stateRoot","transactionsRoot","receiptsRoot","logsBloom"].map(k=>b[k])),...(["difficulty","number","gasLimit","gasUsed","timestamp"].map(k=>bytesQuantity(b[k]))),b.extraData,b.mixHash,b.nonce,bytesQuantity(b.baseFeePerGas)];b.hash=keccak256(toRlp(fields as Hex[]));return b;
}
function normalize(o:{-readonly [K in keyof CircleObservation]:CircleObservation[K]},header:Record<string,unknown>,tx:Hex,nonce:number,gas:number){const h=header.hash,n=header.number;
 o.canonicalBlock=header;o.recheckedBlock=header;o.finalityHead=block(20);o.finalityTag=o.chainId===42161?"finalized":"safe";
 o.transaction={...(o.transaction as object),hash:tx,nonce:q(nonce),gas:q(gas),maxFeePerGas:"0x1312d00",maxPriorityFeePerGas:"0x0",transactionIndex:"0x0",blockNumber:n,blockHash:h};
 const r=o.receipt as Record<string,unknown>;o.receipt={...r,transactionHash:tx,transactionIndex:"0x0",blockNumber:n,blockHash:h,gasUsed:q(gas),effectiveGasPrice:"0x1312d00",logs:(r.logs as Record<string,unknown>[]).map(l=>({...l,transactionHash:tx,transactionIndex:"0x0",blockNumber:n,blockHash:h}))};return o;
}
export async function externalFixture(revisions=false,issuerFee=5n){
 const net=40100n-issuerFee;
 const root=await realpath(await mkdtemp(join(tmpdir(),"circle-external-"))),state=new StateStore(root),repo=new CircleRepository(root),usage=new CircleUsage(state,()=>at),policies=new AllowlistPolicyStore(root);await state.initialize();let op=initial(root);
 for(const [profile,address] of [[op.profile,CIRCLE_SOURCE_OWNER],[op.destinationProfile,circleRoute(143).gasPayer]] as const){const wallet=sealWallet({schemaVersion:"apn.state.v1",profile,profileHash:state.profileHash(profile),address,createdAt:new Date(at).toISOString(),bindingHash:"a".repeat(64)});await state.writeWallet(wallet);await state.writeProviderProfile(projectLegacyLocalProfile(wallet));}
 op=sealCircle({...op,sourceCustody:await evmNativeCustody(state,op.profile),destinationCustody:await evmNativeCustody(state,op.destinationProfile)});
 for(const profile of [op.profile,op.destinationProfile]){let record;const max=revisions?(profile===op.profile?35:17):1;
 for(let i=1;i<=max;i++)record=await policies.stage({profile,...(i===1?{}:{expectedRevision:i-1}),now:new Date(at),policy:{schemaVersion:"apn.allowlist-policy-file.v1",overlayVersion:`old${i}`,accounts:{evm:profile===op.profile?CIRCLE_SOURCE_OWNER:circleRoute(143).gasPayer},effectiveAt:new Date(at-1).toISOString(),expiresAt:new Date(at+1000).toISOString(),admissions:[{chain:"eip155:42161",kind:"token",identifier:CIRCLE_SOURCE_TOKEN,rail:"bridge",maximumPerTransferAtomic:"40100",dailyLimitAtomic:"40100",mechanism:circleMechanism(143)},{chain:"eip155:42161",kind:"native",rail:"bridge",maximumPerTransferAtomic:"30000000000000",dailyLimitAtomic:"75000000000000",mechanism:circleMechanism(143)},{chain:"eip155:143",kind:"native",rail:"bridge",maximumPerTransferAtomic:"100000000000000000",dailyLimitAtomic:"100000000000000000",mechanism:circleMechanism(143)}]}});
 await policies.appendDecision(profile,null,{status:"active",revision:record!.revision,stagedRecordDigest:record!.recordDigest,policyDigest:record!.registry.policyDigest,registry:record!.registry,approvalFingerprint:hashObject(profile),decidedAt:new Date(at).toISOString()});}
 const frozen=await usage.withPolicyLocks([op.profile,op.destinationProfile],()=>usage.policies(op));op=advanceCircle(sealCircle({...op,policies:frozen,transitions:[]}),{},"prepared",at);await repo.save(op);
 op=advanceCircle(op,{usage:await usage.withPolicyLocks([op.profile,op.destinationProfile],()=>usage.reserve(op))},"reserved",at);await repo.save(op);
 const approvalHeader=block(9,[approvalHash]),burnHeader=block(10,[burnHash]);
 const approval=normalize(observation(42161,CIRCLE_SOURCE_OWNER,CIRCLE_SOURCE_TOKEN,encodeCircleApproval(),[event("Approval",CIRCLE_SOURCE_TOKEN,{owner:CIRCLE_SOURCE_OWNER,spender:CIRCLE_MESSENGER,value:40100n},0)]),approvalHeader,approvalHash,1,65536);
 const burn=normalize(source(143),burnHeader,burnHash,2,500000);const approvalProof=verifyCircleApproval(approval,false,"40100"),sourceProof=decodeCircleSource(burn,143);
 for(const role of ["approval","burn"] as const){for(const phase of ["signing_started","sealed","submission_started","submitted","confirmed"] as const){op=advanceCircle(op,{state:"source_unknown",effects:op.effects.map(e=>e.role===role?{...e,phase,...(phase==="signing_started"?{}:{transactionHash:role==="approval"?approvalHash:burnHash,materialHash:"8".repeat(64)}),...(phase==="confirmed"?{proof:role==="approval"?approvalProof:sourceProof}:{})}:e)},`${role}_${phase}`,at);await repo.save(op);}}
 const attestation=await bindCircleAttestation(sourceProof,await iris(sourceProof,message(143,true,issuerFee)),snapshot(143));
 op=advanceCircle(op,{source:sourceProof,attestation,residualAllowanceAtomic:"0",state:"awaiting_mint",usage:await usage.follow(op,"unknown_finality")},"attestation",at);await repo.save(op);
 // Current successors are deliberately different and old authorizations expired; adoption has no mint authority.
 for(const profile of [op.profile,op.destinationProfile]){const head=(await policies.read(profile)).entries.at(-1)!;const record=await policies.stage({profile,expectedRevision:head.revision,now:new Date(at+2000),policy:{schemaVersion:"apn.allowlist-policy-file.v1",overlayVersion:"new-no-circle",accounts:{evm:profile===op.profile?CIRCLE_SOURCE_OWNER:circleRoute(143).gasPayer},effectiveAt:new Date(at+1000).toISOString(),expiresAt:new Date(at+7200000).toISOString(),admissions:[{chain:"eip155:42161",kind:"native",rail:"direct",maximumPerTransferAtomic:"1",dailyLimitAtomic:"1"}]}});await policies.appendDecision(profile,head.entryDigest,{status:"active",revision:record.revision,stagedRecordDigest:record.recordDigest,policyDigest:record.registry.policyDigest,registry:record.registry,approvalFingerprint:hashObject("new"+profile),decidedAt:new Date(at+2000).toISOString()});}
 const unsigned={type:"legacy" as const,chainId:143,nonce:3,gas:500000n,gasPrice:20000000n,to:CIRCLE_TRANSMITTER,value:0n,data:encodeCircleMint(attestation)},raw=await actor.signTransaction(unsigned),txHash=keccak256(raw);
 // Obtain the public signature fields without loading any production wallet.
 const {parseTransaction}=await import("viem"),signed=parseTransaction(raw);const parent=block(9),destHeader=block(10,[txHash],parent.hash as Hex);
 const v2Mint=event("MintAndWithdraw",CIRCLE_MESSENGER,{mintRecipient:CIRCLE_RECIPIENT,amount:net,mintToken:circleRoute(143).token,feeCollected:issuerFee},2) as Record<string,unknown>;v2Mint.topics=[toEventSelector("MintAndWithdraw(address,uint256,address,uint256)"),...(v2Mint.topics as string[]).slice(1)];v2Mint.data=`0x${net.toString(16).padStart(64,"0")}${issuerFee.toString(16).padStart(64,"0")}`;
 const dest=normalize(observation(143,actor.address,CIRCLE_TRANSMITTER,unsigned.data,[event("Transfer",circleRoute(143).token,{from:getAddress(`0x${"0".repeat(40)}`),to:CIRCLE_RECIPIENT,value:net},0),...(issuerFee===0n?[]:[event("Transfer",circleRoute(143).token,{from:getAddress(`0x${"0".repeat(40)}`),to:testFeeRecipient,value:issuerFee},1)]),v2Mint,event("MessageReceived",CIRCLE_TRANSMITTER,{caller:actor.address,sourceDomain:3,nonce:attestation.nonce,sender:circleWord(CIRCLE_MESSENGER),finalityThresholdExecuted:1000,messageBody:attestation.body},3)]),destHeader,txHash,3,500000);
 dest.transaction={...(dest.transaction as object),type:"0x0",chainId:"0x8f",gasPrice:"0x1312d00",r:signed.r,s:signed.s,v:q(signed.v!),from:actor.address};
 const codes=JSON.parse(await readFile(join(process.cwd(),"tests/fixtures/circle-external/pinned-public-code.json"),"utf8")) as Record<string,Record<string,string>>;
 const calls:string[]=[],publicNetwork={request:async(url:string,_method:unknown,body:string|null)=>{const request=JSON.parse(body!),chain=url.includes("arbitrum")?42161:143,{method,params,id}=request;calls.push(method);let result:unknown;
 if(method==="eth_chainId")result=q(chain);
 else if(method==="eth_getTransactionByHash"||method==="eth_getTransactionReceipt"){const o=params[0]===approvalHash?approval:params[0]===burnHash?burn:params[0]===txHash?dest:null;result=o===null?null:method==="eth_getTransactionByHash"?o.transaction:o.receipt;}
 else if(method==="eth_getBlockByNumber"){const tag=params[0];result=tag==="safe"||tag==="finalized"||BigInt(tag)===20n?block(20):chain===42161?(BigInt(tag)===9n?approvalHeader:burnHeader):BigInt(tag)===9n?parent:destHeader;}
 else if(method==="eth_getCode")result=codes[chain]![String(params[0]).toLowerCase()]??"0x";
 else if(method==="eth_getStorageAt"){const p=Object.values(CIRCLE_DEPLOYMENT_PINS[chain as 42161|143]).find(p=>p.address.toLowerCase()===String(params[0]).toLowerCase())!;result=`0x${p.implementation.slice(2).padStart(64,"0")}`;}
 else if(method==="eth_getLogs")result=(dest.receipt as Record<string,unknown>).logs instanceof Array?((dest.receipt as Record<string,unknown>).logs as Record<string,unknown>[]).filter(l=>String(l.address).toLowerCase()===circleRoute(143).token.toLowerCase()):[];
 else if(method==="eth_call"){const abi=[...CIRCLE_RPC_ABI,...parseAbi(["function feeRecipient() view returns(address)"])];const f=decodeFunctionData({abi,data:params[0].data}),tag=params[1],name=f.functionName,args=f.args as readonly unknown[]|undefined;let v:unknown;
 switch(name){case"feeRecipient":if(issuerFee===0n)throw Error("ZERO_FEE_GETTER_FORBIDDEN");v=testFeeRecipient;break;case"localDomain":v=chain===42161?3:15;break;case"remoteTokenMessengers":v=circleWord(CIRCLE_MESSENGER);break;case"remoteTokensToLocalTokens":v=chain===42161?CIRCLE_SOURCE_TOKEN:circleRoute(143).token;break;case"localMinter":v=CIRCLE_MINTER;break;case"localMessageTransmitter":v=CIRCLE_TRANSMITTER;break;case"localTokenMessenger":v=CIRCLE_MESSENGER;break;case"version":case"messageBodyVersion":v=1;break;case"decimals":v=6;break;case"paused":v=false;break;case"allowance":v=typeof tag==="object"&&tag.blockHash===approvalHeader.hash?40100n:0n;break;case"usedNonces":v=1n;break;case"balanceOf":v=typeof tag==="object"&&tag.blockHash===parent.hash?0n:net;break;case"signatureThreshold":case"getNumEnabledAttesters":v=2n;break;case"getEnabledAttester":v=snapshot(143).enabledAttesters[Number(args![0])];break;default:throw Error(name);}
 result=encodeFunctionResult({abi,functionName:name,result:v as never});}
 else throw Error(`FORBIDDEN_NETWORK_METHOD ${method}`);return{status:200,body:JSON.stringify({jsonrpc:"2.0",id,result})};}};
 const secret={load:async()=>{throw Error("PRIVATE_READ");},create:async()=>{throw Error("PRIVATE_CREATE");}};
 const service=new CircleEvmService(state,secret,{APN_ARBITRUM_RPC_URL:"https://arbitrum.example",APN_MONAD_RPC_URL:"https://monad.example"},()=>at+3000,{input:()=>{throw Error("TTY");}} as never,publicNetwork as never);
 return{root,state,repo,usage,policies,op,service,publicNetwork,calls,dest,burn,approval,parent,txHash,secret};
}
