import assert from "node:assert/strict";
import test from "node:test";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { AssetUsageLedger, assetUsageReservationId, validateAssetUsageReservation } from "../../src/asset-usage-ledger.js";
import { seal, withoutDigest, sumUsage } from "../../src/asset-usage-ledger-record.js";
import { canonicalJson, hashObject } from "../../src/canonical.js";
import { sealAssetPolicyRegistry } from "../../src/asset-policy-registry.js";
import type { Cleanup85NativeActualSettlement, VerifiedCleanup85NativeReservation, VerifiedCleanup85NativeSettlement } from "../../src/circle-cleanup85-native-ledger-authority.js";
import { temporaryState } from "./helpers.js";
const account="0x823A3a5BaB1186141b32fC65F8E25Ca24c679Ce7",identity={account,chain:"eip155:42161",asset:{kind:"native" as const,identifier:null}},op="a".repeat(64),key=`apn.cleanup85-native:${op}`;
const at=new Date("2026-10-09T12:00:00.000Z"),later=new Date("2026-10-09T12:01:00.000Z");
function registry(){return sealAssetPolicyRegistry({schemaVersion:"apn.asset-policy-registry.v1",registryVersion:"cleanup85-ledger-test.1",publishedAt:"2026-10-09T00:00:00.000Z",effectiveDate:"2026-10-09",chains:[{chain:identity.chain,family:"evm",name:"Arbitrum",assets:[{kind:"native",identifier:null,symbol:"ETH",decimals:18,rails:{direct:true,gasless:false,x402:false,bridge:false,swap:false},caps:{maximumPerTransferAtomic:"2000000000000",dailyLimitAtomic:"500000000000000"}}]}]});}
async function fixture(t:test.TestContext){const state=await temporaryState();t.after(state.cleanup);const ledger=new AssetUsageLedger(state.root),held=await ledger.reserve({...identity,registry:registry(),rail:"direct",amountAtomic:"2000000000000",idempotencyKey:key,now:at});return {state,ledger,held};}
function proof(policyDigest:string,fee="1000000000000"):Cleanup85NativeActualSettlement{const body={kind:"circle_cleanup85_native_actual" as const,operationId:op,fingerprint:"b".repeat(64),requestBinding:"c".repeat(64),transactionHash:`0x${"d".repeat(64)}`,receiptHash:"e".repeat(64),blockHash:`0x${"f".repeat(64)}`,blockNumberAtomic:"513200000",actualFeeAtomic:fee,nativeConsumedAtomic:(BigInt(fee)+1n).toString(),reservedAtomic:"2000000000000" as const,nativeReservationId:assetUsageReservationId(identity,key),policyDigest};return {...body,outcomeDigest:hashObject(body)};}
function marker(policyDigest:string){return {version:"apn.cleanup85-native-reservation.v1" as const,operationId:op,fingerprint:"b".repeat(64),requestBinding:"c".repeat(64),envelopeHash:"9".repeat(64),signedMaximumDebitAtomic:"1500000000001",reservedAtomic:"2000000000000" as const,policyDigest,activationDigest:"8".repeat(64)};}
function terminal(held:Awaited<ReturnType<AssetUsageLedger["reserve"]>>,p=proof(held.policyDigest)){return seal({...withoutDigest(held),state:"finalized",updatedAt:later.toISOString(),effectAt:later.toISOString(),outcomeDigest:p.outcomeDigest,consumedAtomic:p.nativeConsumedAtomic,cleanup85NativeActual:p,cleanup85NativeReservation:marker(held.policyDigest)});}
test("cleanup85 public record validates fee plus value1 conservation without issuing settlement authority",async t=>{const {held}=await fixture(t),paid=terminal(held);assert.equal(paid.amountAtomic,"2000000000000");assert.equal(paid.consumedAtomic,"1000000000001");assert.equal(sumUsage([paid],later),"1000000000001");assert.deepEqual(validateAssetUsageReservation(structuredClone(paid)),paid);assert.equal(sumUsage([paid],new Date("2026-10-10T00:00:00Z")),"0");});
test("cleanup85 reserve/submitted/unknown keep the entire finite2T hold",async t=>{const {ledger,held}=await fixture(t);for(const state of ["submitted","unknown_finality"] as const){await ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state,now:later});assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");}await assert.rejects(ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:"1".repeat(64),consumedAtomic:"1"}),/consumption/);assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");});
for(const [name,change] of Object.entries({wrongOp:{operationId:"1".repeat(64)},wrongHold:{nativeReservationId:"2".repeat(64)},wrongPolicy:{policyDigest:"3".repeat(64)},wrongConsume:{nativeConsumedAtomic:"1"},overCap:{actualFeeAtomic:"2000000000000",nativeConsumedAtomic:"2000000000001"},invalidBlock:{blockNumberAtomic:"0"},wrongKind:{kind:"generic_native_actual"},invalidReceipt:{receiptHash:"0x"+"e".repeat(64)}}))test(`cleanup85 stored projection rejects ${name}`,async t=>{const {held}=await fixture(t);const {outcomeDigest:_,...body}=proof(held.policyDigest),altered={...body,...change},p={...altered,outcomeDigest:hashObject(altered)};assert.throws(()=>terminal(held,p as Cleanup85NativeActualSettlement));});
for(const [name,change] of Object.entries({token:{asset:{kind:"token",identifier:"0xaf88d065e77c8cC2239327C5EDb3A432268e5831"}},owner:{account:"0x0B4Dd0C3dA001Fa146EEd3f80B01860BEF6B8a14"},chain:{chain:"eip155:1"},rail:{rail:"bridge"},state:{state:"unknown_finality"},reserved:{amountAtomic:"1"}}))test(`cleanup85 exact native reservation rejects ${name}`,async t=>{const {held}=await fixture(t);const good=terminal(held);assert.throws(()=>seal({...withoutDigest(good),...change} as Parameters<typeof seal>[0]));});
test("cleanup85 opaque entry points reject fabricated/serialized authorities before any ledger write",async t=>{const {ledger,held,state}=await fixture(t),path=join(state.root,"asset-usage");const before=await readFile(join(path,(await readdir(path))[0]!,`${held.reservationId}.json`));for(const token of [{kind:"verified-cleanup85-native-reservation"},{kind:"verified-cleanup85-native-settlement"},proof(held.policyDigest),{}]){await assert.rejects(ledger.reserveCleanup85Native(token as VerifiedCleanup85NativeReservation,later),/root_owned_reservation/);await assert.rejects(ledger.settleCleanup85Native(token as VerifiedCleanup85NativeSettlement,later),/root_owned_settlement/);}assert.deepEqual(await readFile(join(path,(await readdir(path))[0]!,`${held.reservationId}.json`)),before);});
test("cleanup85 restored stored projection counts actual debit once; conflicting projection is refused",async t=>{const {ledger,held,state}=await fixture(t),paid=terminal(held),dir=join(state.root,"asset-usage",(await readdir(join(state.root,"asset-usage")))[0]!),path=join(dir,`${held.reservationId}.json`);await writeFile(path,canonicalJson(paid)+"\n");assert.equal((await ledger.usage(identity,later)).amountAtomic,paid.consumedAtomic);assert.equal((await ledger.usage(identity,later)).amountAtomic,paid.consumedAtomic);await assert.rejects(ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:paid.outcomeDigest!}),/outcome/);assert.deepEqual(validateAssetUsageReservation(JSON.parse(await readFile(path,"utf8"))),paid);});
test("ordinary direct records retain full finalization and absence hash compatibility",async t=>{const {ledger,held}=await fixture(t),saved=JSON.stringify(held);assert.equal(held.cleanup85NativeActual,undefined);assert.equal(JSON.stringify(validateAssetUsageReservation(JSON.parse(saved))),saved);const done=await ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:"1".repeat(64)});assert.equal(done.consumedAtomic,undefined);assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");});

for(const [name,change] of Object.entries({operation:{operationId:"1".repeat(64)},fingerprint:{fingerprint:"2".repeat(64)},parent:{requestBinding:"3".repeat(64)},envelope:{envelopeHash:"not-a-hash"},policy:{policyDigest:"4".repeat(64)},activation:{activationDigest:"not-a-hash"},maximum:{signedMaximumDebitAtomic:"999"},extra:{callerApproved:true}}))test(`cleanup85 immutable marker parser rejects ${name} one-field tamper`,async t=>{const {held}=await fixture(t),paid=terminal(held);assert.throws(()=>seal({...withoutDigest(paid),cleanup85NativeReservation:{...paid.cleanup85NativeReservation!,...change}} as Parameters<typeof seal>[0]));});
test("cleanup85 malformed public terminal projection without its frozen marker is rejected",async t=>{const {held}=await fixture(t),paid=terminal(held),{cleanup85NativeReservation:_,...body}=withoutDigest(paid);assert.throws(()=>seal(body));});
test("cleanup85 marker restore carries full unknown hold and prevents generic finalization or key replay",async t=>{const {ledger,held,state}=await fixture(t),marked=seal({...withoutDigest(held),cleanup85NativeReservation:marker(held.policyDigest)}),dir=join(state.root,"asset-usage",(await readdir(join(state.root,"asset-usage")))[0]!),path=join(dir,`${held.reservationId}.json`);await writeFile(path,canonicalJson(marked)+"\n");for(const phase of ["submitted","unknown_finality"] as const){const row=await ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:phase,now:later});assert.deepEqual(row.cleanup85NativeReservation,marked.cleanup85NativeReservation);assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");}const bytes=await readFile(path);await assert.rejects(ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:"1".repeat(64)}));await assert.rejects(ledger.reserve({...identity,registry:registry(),rail:"direct",amountAtomic:"2000000000000",idempotencyKey:key,now:later}),/marker replay/);assert.deepEqual(await readFile(path),bytes);});
