import { AllowlistPolicyStore } from "../../src/allowlist-policy-store.js";
import { activeAssetPolicyFromState } from "../../src/allowlist-active-policy.js";
import { seal as sealUsage,withoutDigest } from "../../src/asset-usage-ledger-record.js";
import test from "node:test";
import assert from "node:assert/strict";
import { mkdir,readFile,writeFile,unlink } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson,domainHash,hashObject } from "../../src/canonical.js";
import { CircleEvmService } from "../../src/circle-v2-evm/runtime.js";
import { circleRoute,CIRCLE_SOURCE_TOKEN } from "../../src/circle-v2-evm/catalog.js";
import { circleMechanism } from "../../src/circle-v2-evm/usage.js";
import { Cleanup85NativeCancellation,verifyCleanup85CancellationAccounting } from "../../src/circle-cleanup85-native-cancellation.js";
import { Cleanup85NativePublicRecords } from "../../src/circle-cleanup85-native-records.js";
import { cleanup85NativeLineage } from "../../src/circle-cleanup85-native-lineage.js";
import { AssetUsageLedger } from "../../src/asset-usage-ledger.js";
import { CLEANUP85_OWNER } from "../../src/circle-cleanup85-native-codec.js";
import { cleanup85PublicState,cleanup85PublicTransport } from "./cleanup85-native-public-fixture.js";
import { activateDirectPolicy,directAdmission } from "./direct-allowlist-helpers.js";
import { temporaryState } from "./helpers.js";
const environment={APN_ARBITRUM_RPC_URL:"https://arbitrum-one-public.nodies.app",APN_SEI_RPC_URL:"https://evm-rpc.sei-apis.com"};
/** Authentic old unsigned operation/request/claims and 83/84 cryptography are replayed offline.
 * Current policy clock/account transport projections are deterministic test state, not live proof.
 * No private key exists; the positive stops at foreground approval after genuine A/B/C admission. */
for(const variant of ["foreground","broker_failure","marker_loss","missing_successor_slot","unrelated_direct"] as const)test(`whole normal successor ${variant} preserves original and full2T`,{timeout:["marker_loss","missing_successor_slot","unrelated_direct"].includes(variant)?10000:30000},async t=>{
 const temp=await temporaryState();t.after(temp.cleanup);const f=await cleanup85PublicState(temp.root),rpc=await cleanup85PublicTransport(),clock=Date.parse("2026-10-09T20:00:00.000Z"),route=circleRoute(1329,"evm-live-seller");
 const frame=JSON.parse(await readFile(new URL("../fixtures/cleanup85-unsigned-retirement/original-a-recovery-intent.json",import.meta.url),"utf8"));
 const records=JSON.parse(await readFile(new URL("../fixtures/cleanup85-unsigned-retirement/native-public-records.json",import.meta.url),"utf8")) as Record<string,unknown>;
 await writeFile(join(temp.root,"circle-cleanup85-recovery",`${f.parent.operationId}-intent.json`),canonicalJson(frame)+"\n");
 for(const [path,body] of Object.entries(records)){if(body===null)continue;await mkdir(join(temp.root,path.split("/").slice(0,-1).join("/")),{recursive:true,mode:0o700});await writeFile(join(temp.root,path),canonicalJson(body)+"\n",{mode:0o600});}
 for(const profile of [f.parent.profile,f.parent.destinationProfile])await activateDirectPolicy(temp.root,profile,{accounts:{evm:profile===f.parent.profile?f.parent.sourceCustody.walletAddress:route.gasPayer},now:new Date(clock),expiresAt:"2026-10-09T20:46:57.000Z",admissions:[directAdmission("eip155:42161",null,{maximumPerTransferAtomic:"2000000000000",dailyLimitAtomic:"500000000000000"}),{chain:"eip155:42161",kind:"token",identifier:CIRCLE_SOURCE_TOKEN,rail:"bridge",maximumPerTransferAtomic:"40100",dailyLimitAtomic:"40100",mechanism:circleMechanism(1329)},{chain:"eip155:42161",kind:"native",rail:"bridge",maximumPerTransferAtomic:"75000000000000",dailyLimitAtomic:"500000000000000",mechanism:circleMechanism(1329)},{chain:"eip155:1329",kind:"native",rail:"bridge",maximumPerTransferAtomic:route.destinationNativeCap,dailyLimitAtomic:route.destinationNativeCap,mechanism:circleMechanism(1329)}]});
 let keys=0,prompts=0;const wrapping={load:async()=>{keys++;throw Error("private_FORBIDDEN");},create:async()=>{throw Error("private_FORBIDDEN");}};
 const cancellation=new Cleanup85NativeCancellation(f.state,wrapping,environment,{https:rpc.https,nativeRpcUrl:"https://arb1.arbitrum.io/rpc",now:()=>clock,approve:async()=>{prompts++;if(variant!=="broker_failure")throw Error("stop_at_successor_foreground");}});
 const originalExecute=cancellation.execute.bind(cancellation);t.mock.method(cancellation,"execute",async(request:Parameters<Cleanup85NativeCancellation["execute"]>[0])=>{rpc.setPhase("B_execute");return originalExecute(request);});
 const service=new CircleEvmService(f.state,wrapping,environment,()=>clock,{},rpc.https,{cancellation,verifyCancellationAccounting:verifyCleanup85CancellationAccounting});
 rpc.setPhase("A_initial_prepare");const request=await service.prepareCleanup85Recovery(f.parent.operationId),lineage=await cleanup85NativeLineage(f.state,request),original=(await f.state.findOperation(lineage.originalOperationId))!;
 assert.equal(original.state,"failed_before_effect");const originalBytes=await readFile(join(temp.root,"operations",original.profileHash,`${original.operationId}.json`)),slotBefore=await new Cleanup85NativePublicRecords(temp.root).load(f.parent.operationId,"slot");
 rpc.setPhase("A_cancel_outer");if(variant==="broker_failure")assert.equal((await service.cancelCleanup85(f.parent.operationId)).phase,"unknown");else await assert.rejects(service.cancelCleanup85(f.parent.operationId),/stop_at_successor_foreground/);assert.equal(prompts,1);assert.equal(keys,variant==="broker_failure"?1:0);
 const successor=(await f.state.findOperation(lineage.operationId))!;assert.notEqual(successor.operationId,original.operationId);assert.equal(successor.state,variant==="broker_failure"?"started":"awaiting_approval");assert.equal(successor.economics!.nonceAtomic,"85");assert.equal(successor.amountAtomic,"1");assert.equal(successor.transactionData,"0x");assert.equal(successor.evm!.maxFeeWei,"2000000000000");assert.equal(successor.evm!.cleanup85Cancellation!.version,"apn.circle-cleanup85-native-binding.v2");
 const ledger=new AssetUsageLedger(temp.root),identity={account:CLEANUP85_OWNER,chain:"eip155:42161",asset:{kind:"native" as const,identifier:null}};assert.equal(await ledger.load(identity,original.evm!.cleanup85Cancellation!.nativeReservationId),null);assert.equal((await ledger.load(identity,successor.evm!.cleanup85Cancellation!.nativeReservationId))!.amountAtomic,"2000000000000");
 assert.deepEqual(await readFile(join(temp.root,"operations",original.profileHash,`${original.operationId}.json`)),originalBytes);assert.deepEqual(await new Cleanup85NativePublicRecords(temp.root).load(f.parent.operationId,"slot"),slotBefore);assert.ok(rpc.rows.every(row=>row.method!=="eth_sendRawTransaction"));
 if(variant==="broker_failure"){const signingPath=join(temp.root,"direct-public-effects",successor.profileHash,`${successor.operationId}.signing.json`),signing=await readFile(signingPath);assert.equal((await service.cancelCleanup85(f.parent.operationId)).phase,"unknown");assert.equal(keys,1);assert.equal(prompts,1);assert.deepEqual(await readFile(signingPath),signing);}
 if(variant==="unrelated_direct"){const active=activeAssetPolicyFromState(await new AllowlistPolicyStore(temp.root).read(f.parent.profile),new Date(clock))!;const other=await ledger.reserve({...identity,registry:active.registry,rail:"direct",amountAtomic:"1",idempotencyKey:"unrelated-direct-unit-accounting-only",now:new Date(clock)});assert.equal((await ledger.transition({...identity,reservationId:other.reservationId,policyDigest:other.policyDigest,state:"failed_before_effect",outcomeDigest:hashObject("unrelated test-only unsigned row"),now:new Date(clock)})).state,"failed_before_effect");assert.equal((await ledger.load(identity,successor.evm!.cleanup85Cancellation!.nativeReservationId))!.state,"reserved");}
 if(variant==="marker_loss"||variant==="missing_successor_slot"){if(variant==="missing_successor_slot")await unlink(join(temp.root,"circle-cleanup85-native",`${f.parent.operationId}-successor-slot.json`));const path=join(temp.root,"asset-usage",domainHash("apn.asset-usage-bucket.v1",canonicalJson(identity)),`${successor.evm!.cleanup85Cancellation!.nativeReservationId}.json`),body=JSON.parse(await readFile(path,"utf8"));delete body.cleanup85NativeReservation;await writeFile(path,canonicalJson(sealUsage(withoutDigest(body)))+"\n",{mode:0o600});const before=await readFile(path);await assert.rejects(ledger.transition({...identity,reservationId:body.reservationId,policyDigest:body.policyDigest,state:"failed_before_effect",outcomeDigest:hashObject("forbidden marker-lost successor"),now:new Date(clock)}),variant==="missing_successor_slot"?/reservation_successor_slot_missing/:/opaque canonical settlement required/);assert.deepEqual(await readFile(path),before);}
 t.diagnostic(`OFFLINE phase/origin counts=${canonicalJson(rpc.rows.reduce<Record<string,number>>((counts,row)=>{const key=`${row.phase} ${row.endpoint}`;counts[key]=(counts[key]??0)+1;return counts;},{}))}`);
 t.diagnostic(`OFFLINE underlying public transport attempts including normal A expiry preparation and B successor preSIGN=${rpc.rows.length}; no live HTTP/private key/crypto sign/send`);
});
