import { StateStore, sealOperation, appendTransition } from "../../src/state.js";
import { STATE_VERSION } from "../../src/constants.js";
import { evmDirectFingerprint } from "../../src/evm-direct.js";
import { resolveEvmAsset } from "../../src/evm-asset.js";
import { validateEconomics } from "../../src/transfer-policy.js";
import { CLEANUP85_REQUEST, CLEANUP85_RECIPIENT } from "../../src/circle-cleanup85-native-codec.js";
import { Cleanup85NativePublicRecords, loadCleanup85NativeReservationIdentity } from "../../src/circle-cleanup85-native-records.js";
import assert from "node:assert/strict";
import test from "node:test";
import { readFile, readdir, writeFile, unlink } from "node:fs/promises";
import { join } from "node:path";
import { AssetUsageLedger, assetUsageReservationId, validateAssetUsageReservation } from "../../src/asset-usage-ledger.js";
import { seal, withoutDigest, sumUsage, idempotency } from "../../src/asset-usage-ledger-record.js";
import { canonicalJson, hashObject } from "../../src/canonical.js";
import { sealAssetPolicyRegistry } from "../../src/asset-policy-registry.js";
import type { Cleanup85NativeActualSettlement, VerifiedCleanup85NativeReservation, VerifiedCleanup85NativeSettlement } from "../../src/circle-cleanup85-native-ledger-authority.js";
import { temporaryState } from "./helpers.js";
const account="0x823A3a5BaB1186141b32fC65F8E25Ca24c679Ce7",identity={account,chain:"eip155:42161",asset:{kind:"native" as const,identifier:null}},op="a".repeat(64),key=`apn.cleanup85-native:${op}`;
const at=new Date("2026-10-09T12:00:00.000Z"),later=new Date("2026-10-09T12:01:00.000Z");
function registry(){return sealAssetPolicyRegistry({schemaVersion:"apn.asset-policy-registry.v1",registryVersion:"cleanup85-ledger-test.1",publishedAt:"2026-10-09T00:00:00.000Z",effectiveDate:"2026-10-09",chains:[{chain:identity.chain,family:"evm",name:"Arbitrum",assets:[{kind:"native",identifier:null,symbol:"ETH",decimals:18,rails:{direct:true,gasless:false,x402:false,bridge:false,swap:false},caps:{maximumPerTransferAtomic:"2000000000000",dailyLimitAtomic:"500000000000000"}}]}]});}
async function fixture(t:test.TestContext){const state=await temporaryState();t.after(state.cleanup);const ledger=new AssetUsageLedger(state.root),held=await ledger.reserve({...identity,registry:registry(),rail:"direct",amountAtomic:"2000000000000",idempotencyKey:"ordinary-native-data-fixture",now:at});const finite=seal({...withoutDigest(held),reservationId:assetUsageReservationId(identity,key),idempotencyHash:idempotency(key)}),dir=join(state.root,"asset-usage",(await readdir(join(state.root,"asset-usage")))[0]!);await unlink(join(dir,`${held.reservationId}.json`));await writeFile(join(dir,`${finite.reservationId}.json`),canonicalJson(finite)+"\n",{mode:0o600});return {state,ledger,held:finite};}
function proof(policyDigest:string,fee="1000000000000"):Cleanup85NativeActualSettlement{const body={kind:"circle_cleanup85_native_actual" as const,operationId:op,fingerprint:"b".repeat(64),requestBinding:"c".repeat(64),transactionHash:`0x${"d".repeat(64)}`,receiptHash:"e".repeat(64),blockHash:`0x${"f".repeat(64)}`,blockNumberAtomic:"513200000",actualFeeAtomic:fee,nativeConsumedAtomic:(BigInt(fee)+1n).toString(),reservedAtomic:"2000000000000" as const,nativeReservationId:assetUsageReservationId(identity,key),policyDigest};return {...body,outcomeDigest:hashObject(body)};}
function marker(policyDigest:string){return {version:"apn.cleanup85-native-reservation.v1" as const,operationId:op,fingerprint:"b".repeat(64),requestBinding:"c".repeat(64),envelopeHash:"9".repeat(64),signedMaximumDebitAtomic:"1500000000001",reservedAtomic:"2000000000000" as const,policyDigest,activationDigest:"8".repeat(64)};}
function terminal(held:Awaited<ReturnType<AssetUsageLedger["reserve"]>>,p=proof(held.policyDigest)){return seal({...withoutDigest(held),reservationId:assetUsageReservationId(identity,key),idempotencyHash:idempotency(key),state:"finalized",updatedAt:later.toISOString(),effectAt:later.toISOString(),outcomeDigest:p.outcomeDigest,consumedAtomic:p.nativeConsumedAtomic,cleanup85NativeActual:p,cleanup85NativeReservation:marker(held.policyDigest)});}
test("cleanup85 public record validates fee plus value1 conservation without issuing settlement authority",async t=>{const {held}=await fixture(t),paid=terminal(held);assert.equal(paid.amountAtomic,"2000000000000");assert.equal(paid.consumedAtomic,"1000000000001");assert.equal(sumUsage([paid],later),"1000000000001");assert.deepEqual(validateAssetUsageReservation(structuredClone(paid)),paid);assert.equal(sumUsage([paid],new Date("2026-10-10T00:00:00Z")),"0");});
test("cleanup85 reserve/submitted/unknown keep the entire finite2T hold",async t=>{const {ledger,held}=await fixture(t);for(const state of ["submitted","unknown_finality"] as const){await ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state,now:later});assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");}await assert.rejects(ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:"1".repeat(64),consumedAtomic:"1"}),/consumption/);assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");});
for(const [name,change] of Object.entries({wrongOp:{operationId:"1".repeat(64)},wrongHold:{nativeReservationId:"2".repeat(64)},wrongPolicy:{policyDigest:"3".repeat(64)},wrongConsume:{nativeConsumedAtomic:"1"},overCap:{actualFeeAtomic:"2000000000000",nativeConsumedAtomic:"2000000000001"},invalidBlock:{blockNumberAtomic:"0"},wrongKind:{kind:"generic_native_actual"},invalidReceipt:{receiptHash:"0x"+"e".repeat(64)}}))test(`cleanup85 stored projection rejects ${name}`,async t=>{const {held}=await fixture(t);const {outcomeDigest:_,...body}=proof(held.policyDigest),altered={...body,...change},p={...altered,outcomeDigest:hashObject(altered)};assert.throws(()=>terminal(held,p as Cleanup85NativeActualSettlement));});
for(const [name,change] of Object.entries({token:{asset:{kind:"token",identifier:"0xaf88d065e77c8cC2239327C5EDb3A432268e5831"}},owner:{account:"0x0B4Dd0C3dA001Fa146EEd3f80B01860BEF6B8a14"},chain:{chain:"eip155:1"},rail:{rail:"bridge"},state:{state:"unknown_finality"},reserved:{amountAtomic:"1"}}))test(`cleanup85 exact native reservation rejects ${name}`,async t=>{const {held}=await fixture(t);const good=terminal(held);assert.throws(()=>seal({...withoutDigest(good),...change} as Parameters<typeof seal>[0]));});
test("cleanup85 opaque entry points reject fabricated/serialized authorities before any ledger write",async t=>{const {ledger,held,state}=await fixture(t),path=join(state.root,"asset-usage");const before=await readFile(join(path,(await readdir(path))[0]!,`${held.reservationId}.json`));for(const token of [{kind:"verified-cleanup85-native-reservation"},{kind:"verified-cleanup85-native-settlement"},proof(held.policyDigest),{}]){await assert.rejects(ledger.reserveCleanup85Native(token as VerifiedCleanup85NativeReservation,later),/root_owned_reservation/);await assert.rejects(ledger.settleCleanup85Native(token as VerifiedCleanup85NativeSettlement,later),/root_owned_settlement/);}assert.deepEqual(await readFile(join(path,(await readdir(path))[0]!,`${held.reservationId}.json`)),before);});
test("cleanup85 restored stored projection counts actual debit once; conflicting projection is refused",async t=>{const {ledger,held,state}=await fixture(t),paid=terminal(held),dir=join(state.root,"asset-usage",(await readdir(join(state.root,"asset-usage")))[0]!),path=join(dir,`${held.reservationId}.json`);await writeFile(path,canonicalJson(paid)+"\n");assert.equal((await ledger.usage(identity,later)).amountAtomic,paid.consumedAtomic);assert.equal((await ledger.usage(identity,later)).amountAtomic,paid.consumedAtomic);await assert.rejects(ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:paid.outcomeDigest!}),/opaque canonical settlement/);assert.deepEqual(validateAssetUsageReservation(JSON.parse(await readFile(path,"utf8"))),paid);});
test("ordinary direct records retain full finalization and absence hash compatibility",async t=>{const {ledger,held}=await fixture(t),saved=JSON.stringify(held);assert.equal(held.cleanup85NativeActual,undefined);assert.equal(JSON.stringify(validateAssetUsageReservation(JSON.parse(saved))),saved);const done=await ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:"1".repeat(64)});assert.equal(done.consumedAtomic,undefined);assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");});

for(const [name,change] of Object.entries({operation:{operationId:"1".repeat(64)},fingerprint:{fingerprint:"2".repeat(64)},parent:{requestBinding:"3".repeat(64)},envelope:{envelopeHash:"not-a-hash"},policy:{policyDigest:"4".repeat(64)},activation:{activationDigest:"not-a-hash"},maximum:{signedMaximumDebitAtomic:"999"},extra:{callerApproved:true}}))test(`cleanup85 immutable marker parser rejects ${name} one-field tamper`,async t=>{const {held}=await fixture(t),paid=terminal(held);assert.throws(()=>seal({...withoutDigest(paid),cleanup85NativeReservation:{...paid.cleanup85NativeReservation!,...change}} as Parameters<typeof seal>[0]));});
test("cleanup85 malformed public terminal projection without its frozen marker is rejected",async t=>{const {held}=await fixture(t),paid=terminal(held),{cleanup85NativeReservation:_,...body}=withoutDigest(paid);assert.throws(()=>seal(body));});
test("cleanup85 marker restore carries full unknown hold and prevents generic finalization or key replay",async t=>{const {ledger,held,state}=await fixture(t),marked=seal({...withoutDigest(held),reservationId:assetUsageReservationId(identity,key),idempotencyHash:idempotency(key),cleanup85NativeReservation:marker(held.policyDigest)}),dir=join(state.root,"asset-usage",(await readdir(join(state.root,"asset-usage")))[0]!),path=join(dir,`${held.reservationId}.json`);await writeFile(path,canonicalJson(marked)+"\n");for(const phase of ["submitted","unknown_finality"] as const){const row=await ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:phase,now:later});assert.deepEqual(row.cleanup85NativeReservation,marked.cleanup85NativeReservation);assert.equal((await ledger.usage(identity,later)).amountAtomic,"2000000000000");}const bytes=await readFile(path);await assert.rejects(ledger.transition({...identity,reservationId:held.reservationId,policyDigest:held.policyDigest,state:"finalized",now:later,outcomeDigest:"1".repeat(64)}));await assert.rejects(ledger.reserve({...identity,registry:registry(),rail:"direct",amountAtomic:"2000000000000",idempotencyKey:key,now:later}),/namespace requires|marker replay/);assert.deepEqual(await readFile(path),bytes);});

async function markedFixture(t:test.TestContext,stateName:"reserved"|"unknown_finality"){const f=await fixture(t),row=seal({...withoutDigest(f.held),reservationId:assetUsageReservationId(identity,key),idempotencyHash:idempotency(key),state:stateName,updatedAt:stateName==="reserved"?at.toISOString():later.toISOString(),cleanup85NativeReservation:marker(f.held.policyDigest)}),dir=join(f.state.root,"asset-usage",(await readdir(join(f.state.root,"asset-usage")))[0]!),path=join(dir,`${row.reservationId}.json`);await writeFile(path,canonicalJson(row)+"\n");return {...f,row,path};}
for(const source of ["reserved","unknown_finality"] as const)for(const target of ["released_unsubmitted","failed_before_effect","failed_confirmed_revert","finalized"] as const)test(`cleanup85 ${source} generic ${target} refuses ordinary and forged contexts without releasing capacity`,async t=>{const f=await markedFixture(t,source),bytes=await readFile(f.path);for(const forged of [{},{cleanup85NativeActual:proof(f.held.policyDigest),cleanup85NativeReservation:undefined,authority:{kind:"verified-cleanup85-native-settlement"},approved:true}]){await assert.rejects(f.ledger.transition({...identity,reservationId:f.row.reservationId,policyDigest:f.row.policyDigest,state:target,now:later,outcomeDigest:"1".repeat(64),...forged}),/opaque canonical settlement/);assert.deepEqual(await readFile(f.path),bytes);assert.equal((await f.ledger.usage(identity,later)).amountAtomic,"2000000000000");}});
for(const phase of ["reserved","unknown_finality"] as const)test(`cleanup85 ${phase} callback release refuses before any callback or ledger mutation`,async t=>{const f=await markedFixture(t,phase),bytes=await readFile(f.path);let callbacks=0;await assert.rejects(f.ledger.releaseDirectReservedAfter(f.row,async()=>{callbacks++;return {value:"released",now:later,outcomeDigest:"1".repeat(64)};}),/opaque canonical settlement/);assert.equal(callbacks,0);assert.deepEqual(await readFile(f.path),bytes);assert.equal((await f.ledger.usage(identity,later)).amountAtomic,"2000000000000");});
for(const phase of ["released_unsubmitted","failed_before_effect","failed_confirmed_revert"] as const)test(`cleanup85 restored marker-only ${phase} is not a valid stored capacity release`,async t=>{const f=await markedFixture(t,"unknown_finality");assert.throws(()=>seal({...withoutDigest(f.row),state:phase,updatedAt:later.toISOString(),effectAt:null,outcomeDigest:"1".repeat(64)}));});
test("cleanup85 internal reserve cannot treat a private-method plain body as authority",async t=>{const f=await fixture(t),bytes=await readFile(join(f.state.root,"asset-usage",(await readdir(join(f.state.root,"asset-usage")))[0]!,`${f.held.reservationId}.json`));const reserveBound=(f.ledger as unknown as {reserveBound(input:unknown,authority:unknown):Promise<unknown>}).reserveBound.bind(f.ledger);await assert.rejects(reserveBound({...identity,registry:registry(),rail:"direct",amountAtomic:"2000000000000",idempotencyKey:key,now:later},{operation:{operationId:op},reservedAtomic:"2000000000000",approved:true}),/root_owned_reservation/);assert.deepEqual(await readFile(join(f.state.root,"asset-usage",(await readdir(join(f.state.root,"asset-usage")))[0]!,`${f.held.reservationId}.json`)),bytes);});

test("generic reserve cannot create the finite cleanup85 namespace without authority",async t=>{const state=await temporaryState();t.after(state.cleanup);const ledger=new AssetUsageLedger(state.root);await assert.rejects(ledger.reserve({...identity,registry:registry(),rail:"direct",amountAtomic:"2000000000000",idempotencyKey:key,now:at}),/namespace requires/);assert.equal((await ledger.usage(identity,at)).amountAtomic,"0");});

/** Actual StateStore public operation/slot fixture only, not an opaque reservation admission. */
async function strippedDurableFixture(t:test.TestContext,phase:"reserved"|"unknown_finality"){
 const temp=await temporaryState();t.after(temp.cleanup);const state=new StateStore(temp.root),ledger=new AssetUsageLedger(temp.root),r={...CLEANUP85_REQUEST,recoveryBinding:"1".repeat(64),parentIntentHash:"2".repeat(64)},id=state.operationId("evm-live-buyer",`cleanup85-native:${r.recoveryBinding}`),nativeKey=`apn.cleanup85-native:${id}`;
 const custody=(profile:string,address:typeof account|typeof CLEANUP85_RECIPIENT)=>({schemaVersion:"apn.evm-native-custody.v1" as const,profileHash:state.profileHash(profile),walletAddress:address,walletBindingHash:"3".repeat(64),walletCreatedAt:at.toISOString(),providerId:"local" as const,providerAccountBindingHash:"3".repeat(64),providerCapabilityHash:"4".repeat(64),providerRevision:1});
 const p=registry(),economics=validateEconomics("85",{gasLimitAtomic:"25000",maxFeePerGasAtomic:"45000000",maxPriorityFeePerGasAtomic:"1"}),rid=assetUsageReservationId(identity,nativeKey),evm={schemaVersion:"apn.evm-direct.v1" as const,asset:resolveEvmAsset({chainId:42161,token:"native"},18),transactionTo:CLEANUP85_RECIPIENT,valueAtomic:"1",maxFeeWei:"2000000000000",nativeCustody:custody("evm-live-buyer",account),cleanup85Cancellation:{version:"apn.circle-cleanup85-native-binding.v1" as const,request:r,recipientCustody:custody("default",CLEANUP85_RECIPIENT),activationDigest:"5".repeat(64),nativeReservationId:rid,nativeReserveAtomic:"2000000000000" as const},feeQuote:{chainId:42161 as const,l1DataFeeUpperWei:"0",operatorFeeUpperWei:"0",maximumExecutionFeeWei:economics.maximumGasCostAtomic,totalQuoteWei:economics.maximumGasCostAtomic,totalFeeEnforcedOnchain:false as const,feeModel:"arbitrum-inclusive" as const,blockNumberAtomic:"513200000",blockHash:`0x${"6".repeat(64)}` as `0x${string}`,rpcOrigin:"https://arb1.arbitrum.io",observedAt:at.toISOString()}} as const;
 const frozen={operationId:id,profile:"evm-live-buyer",chainId:42161,token:evm.asset.address,walletAddress:account,recipient:CLEANUP85_RECIPIENT,amountAtomic:"1",transactionData:"0x" as const,economics,preparedAt:at.toISOString(),expiresAt:"2026-10-09T12:10:00.000Z",evm} as const,o=sealOperation({...frozen,schemaVersion:STATE_VERSION,profileHash:state.profileHash(frozen.profile),idempotencyHash:state.idempotencyHash(`cleanup85-native:${r.recoveryBinding}`),requestHash:hashObject({method:"apn.cleanup85-native.v1",request:r}),fingerprint:evmDirectFingerprint(frozen),amountDecimal:"0.000000000000000001",preparedBlockNumberAtomic:"513200000",allowlist:{schemaVersion:"apn.direct-allowlist.v1",policyDigest:p.policyDigest,policyRevision:1},state:"awaiting_approval",terminal:false,reason:"prepared_and_frozen",proofClass:"durable_pre_effect",transitions:appendTransition([],{at:at.toISOString(),state:"awaiting_approval",terminal:false,reason:"prepared_and_frozen",proofClass:"durable_pre_effect"})});
 await state.initialize();await state.writeOperation(o);await new Cleanup85NativePublicRecords(temp.root).publish(r.parentOperationId,"slot",{version:"apn.cleanup85-single-cancellation.v1",parentOperationId:r.parentOperationId,oldCleanupMaterialHash:r.oldCleanupMaterialHash,requestBinding:hashObject(r),operationId:id,fingerprint:o.fingerprint});assert.equal((await loadCleanup85NativeReservationIdentity(state))?.nativeReservationId,rid);
 const ordinary=await ledger.reserve({...identity,registry:p,rail:"direct",amountAtomic:"2000000000000",idempotencyKey:"ordinary-restored-data",now:at}),row=seal({...withoutDigest(ordinary),reservationId:rid,idempotencyHash:idempotency(nativeKey),state:phase,updatedAt:phase==="reserved"?at.toISOString():later.toISOString()}),dir=join(temp.root,"asset-usage",(await readdir(join(temp.root,"asset-usage")))[0]!),path=join(dir,`${rid}.json`);await unlink(join(dir,`${ordinary.reservationId}.json`));await writeFile(path,canonicalJson(row)+"\n",{mode:0o600});return {state,ledger,row,path};
}
for(const phase of ["reserved","unknown_finality"] as const)test(`actual durable native operation blocks generic release after ${phase} marker removal`,async t=>{const f=await strippedDurableFixture(t,phase),bytes=await readFile(f.path);for(const target of ["released_unsubmitted","failed_before_effect","failed_confirmed_revert","finalized"] as const){await assert.rejects(f.ledger.transition({...identity,reservationId:f.row.reservationId,policyDigest:f.row.policyDigest,state:target,now:later,outcomeDigest:"1".repeat(64)}),/marker is missing/);assert.deepEqual(await readFile(f.path),bytes);assert.equal((await f.ledger.usage(identity,later)).amountAtomic,"2000000000000");}if(phase==="reserved"){let calls=0;await assert.rejects(f.ledger.releaseDirectReservedAfter(f.row,async()=>{calls++;return {value:0,now:later,outcomeDigest:"1".repeat(64)};}),/marker is missing/);assert.equal(calls,0);assert.deepEqual(await readFile(f.path),bytes);}});
