import { createKeyPairSignerFromPrivateKeyBytes, getAddressEncoder, getTransactionDecoder, signTransaction, getBase64EncodedWireTransaction, getSignatureFromTransaction } from "@solana/kit";
import { join } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import { canonicalJson, domainHash, sha256 } from "../../src/canonical.js";
import { ChainAccountStore } from "../../src/chain-account-store.js";
import { StateStore } from "../../src/state.js";
import { AssetUsageLedger } from "../../src/asset-usage-ledger.js";
import { sealAssetPolicyRegistry } from "../../src/asset-policy-registry.js";
import { temporaryState } from "./helpers.js";
import { fixture, mutate } from "../fixtures/jupiter-v1/material.js";
import { simulation } from "../fixtures/jupiter-v1/scenarios.js";
import { associatedTokenAddress } from "../../src/swap/orca-solana/accounts.js";
import { WRAPPED_SOL_MINT, SOLANA_USDC_MINT, TOKEN_PROGRAM } from "../../src/swap/jupiter-solana/catalog.js";
import { jupiterV1Lifetime } from "../../src/swap/jupiter-solana/v1-codec.js";
import { jupiterV1MaterialDigest, SavedJupiterV1MaterialStore } from "../../src/swap/jupiter-solana/v1-material.js";
import { guardJupiterV1WhirlpoolMaterial } from "../../src/swap/jupiter-solana/v1-guard.js";
import { proveJupiterV1Quote, snapshotFromJupiterV1QuoteProof, proveJupiterV1Simulation } from "../../src/swap/jupiter-solana/v1-proof.js";
import { newSwapOperation, SWAP_OPERATION_SCHEMA, validateSwapOperation } from "../../src/swap/model.js";
import { transitionSwapOperation } from "../../src/swap/transitions.js";
import { JupiterV1ExecutionBindingStore, createJupiterV1ExecutionBinding } from "../../src/swap/jupiter-solana/v1-effects.js";
import { jupiterV1AccountBindingHash } from "../../src/swap/jupiter-solana/v1-admission.js";
import { JUPITER_V1_OLD_ROUTE as route } from "../../src/swap/jupiter-solana/v1-route-config.js";
import { swapMechanismDigest } from "../../src/swap/pin.js";
import { HISTORICAL_JUPITER_IDS } from "../../src/swap/jupiter-solana/historical-authenticator.js";
export async function historicalFixture(options: { cap?: string; mutateSealedEffect?: (effect: import("../../src/direct-rail-ports.js").RailSignedEffect) => import("../../src/direct-rail-ports.js").RailSignedEffect } = {}) {
  const temp = await temporaryState(), state = new StateStore(temp.root); await state.initialize();
  const seed = Buffer.alloc(32, 21), signer = await createKeyPairSignerFromPrivateKeyBytes(seed), owner = signer.address;
  const old = fixture(), source = await associatedTokenAddress(owner, WRAPPED_SOL_MINT, TOKEN_PROGRAM), dest = await associatedTokenAddress(owner, SOLANA_USDC_MINT, TOKEN_PROGRAM);
  const oldDest = old.rawBuildResponse.swapInstruction.accounts[3]!.pubkey;
  const mapping = new Map([[old.payer,owner],[old.rawBuildResponse.swapInstruction.accounts[2]!.pubkey,source],[oldDest,dest]]);
  const m = mutate(old, v => {
    v.payer=owner; if (options.cap !== undefined) v.maximumNativeExpenseLamports=options.cap;
    for (const ix of [...v.rawBuildResponse.computeBudgetInstructions,...v.rawBuildResponse.setupInstructions,v.rawBuildResponse.swapInstruction,v.rawBuildResponse.cleanupInstruction]) for (const a of ix.accounts) a.pubkey=mapping.get(a.pubkey)??a.pubkey;
    for (const a of v.semanticAccounts) { const prior=a.address;a.address=mapping.get(a.address)??a.address;if(prior===oldDest){const d=Buffer.from(a.dataBase64,"base64");Buffer.from(getAddressEncoder().encode(owner)).copy(d,32);a.dataBase64=d.toString("base64");} }
  });
  const {materialDigest:_,...body}=m, execution={...body,lifetime:jupiterV1Lifetime(body.rawBuildResponse)}, material={...execution,materialDigest:jupiterV1MaterialDigest(execution)};
  const guarded=await guardJupiterV1WhirlpoolMaterial(material), sim=simulation(guarded), now=new Date();
  const input={profile:"solana-local",account:owner,recipient:owner,amountAtomic:"1000000",slippageBps:50,now};
  const proof=await proveJupiterV1Quote({call:async()=>sim},material,input), quote=snapshotFromJupiterV1QuoteProof(proof,material,input);
  const prepared={quote,approvalCapAtomic:"0" as const,execution:material,gasOrEnergy:{networkFeeLamports:material.networkFeeLamports!,tokenAccountRentLamports:material.tokenAccountRentLamports,maximumNativeExpenseLamports:material.maximumNativeExpenseLamports}};
  const materials=new SavedJupiterV1MaterialStore(temp.root);await materials.save(prepared);
  const wrapping={load:async()=>Buffer.alloc(32,77),create:async()=>Buffer.alloc(32,77)}, custody=new ChainAccountStore(temp.root,wrapping);
  const account=await custody.ensureLocal({profile:"solana-local",rail:"solana",create:async()=>({address:owner,seed:Buffer.from(seed)})});
  const registry=sealAssetPolicyRegistry({schemaVersion:"apn.asset-policy-registry.v1",registryVersion:"historical-test.1",publishedAt:new Date(now.getTime()-2000).toISOString(),effectiveDate:now.toISOString().slice(0,10),effectiveAt:new Date(now.getTime()-1000).toISOString(),expiresAt:new Date(now.getTime()+86400000).toISOString(),chains:[{chain:route.mechanismPin.chain,family:"solana",name:"Solana",assets:[{kind:"native",identifier:null,symbol:"SOL",decimals:9,rails:{direct:false,gasless:false,x402:false,bridge:false,swap:true},caps:{maximumPerTransferAtomic:"1000000",dailyLimitAtomic:"2000000"},mechanismPins:{swap:route.mechanismPin}}]}]});
  const ledger=new AssetUsageLedger(temp.root), lease=await ledger.reserve({account:owner,chain:quote.sourceAsset.chain,asset:{kind:"native",identifier:null},registry,rail:"swap",amountAtomic:"1000000",idempotencyKey:"historical-test",now});
  let op=newSwapOperation({operationId:HISTORICAL_JUPITER_IDS[0],idempotencyHash:sha256("historical-test"),quote,policyDigest:registry.policyDigest,policyVersion:registry.registryVersion,protocolRegistryDigest:route.protocolRegistry.registryDigest,protocolRegistryVersion:route.protocolRegistry.registryVersion,mechanismDigest:swapMechanismDigest(route.mechanismPin),approvalCapAtomic:"0",now});
  for(const phase of ["prepared","awaiting_approval"] as const)op=transitionSwapOperation(op,phase,{},now);
  op=transitionSwapOperation(op,"reserved",{usageLease:lease},now);
  const markerBody={operationId:op.operationId,operationIntegrityHash:op.integrityHash,unsignedTransactionPayloadHash:quote.unsignedTransactionPayloadHash,markedAt:now.toISOString()};
  op=transitionSwapOperation(op,"submitting",{submissionMarker:{operationIntegrityHash:markerBody.operationIntegrityHash,unsignedTransactionPayloadHash:markerBody.unsignedTransactionPayloadHash,markedAt:markerBody.markedAt,markerHash:domainHash("apn.swap-submission-marker.v1",canonicalJson(markerBody))}},now);
  const admission={account,accountBindingHash:jupiterV1AccountBindingHash(account),policyDigest:registry.policyDigest,activationDigest:"a".repeat(64),admissionHash:"b".repeat(64)};
  const bindings=new JupiterV1ExecutionBindingStore(temp.root), simulationProof=await proveJupiterV1Simulation({call:async()=>sim},guarded), binding=createJupiterV1ExecutionBinding(op,prepared,admission,simulationProof,now,material);
  await bindings.bindPrepared(op,admission,prepared);await bindings.save(op,binding,prepared);await bindings.saveFresh(op,material,simulationProof);
  const signed=await signTransaction([signer.keyPair],getTransactionDecoder().decode(Buffer.from(binding.unsignedPayload,"base64"))),rawPayload=getBase64EncodedWireTransaction(signed);
  const effect={operationId:op.operationId,fingerprint:binding.bindingHash,transactionId:getSignatureFromTransaction(signed),rawPayload,rawPayloadHash:sha256(rawPayload)};
  await bindings.saveSignature(op,binding,effect);await bindings.claim(op,binding,effect,now);await custody.saveEffect(account,options.mutateSealedEffect?.(effect) ?? effect);
  const unknownLease=await ledger.transition({account:owner,chain:quote.sourceAsset.chain,asset:{kind:"native",identifier:null},reservationId:lease.reservationId,policyDigest:registry.policyDigest,state:"unknown_finality",now});
  op=transitionSwapOperation(op,"unknown_finality",{usageLease:unknownLease},now);
  await mkdir(join(temp.root,"swap-operations",op.ownerProfileHash),{recursive:true,mode:0o700});
  const opPath=join(temp.root,"swap-operations",op.ownerProfileHash,`${op.operationId}.json`);
  await writeFile(opPath,canonicalJson(validateSwapOperation(op)),{mode:0o600});
  const resealOperation=(v:typeof op)=>{const {integrityHash:__,...b}=v;return {...b,integrityHash:domainHash(SWAP_OPERATION_SCHEMA,canonicalJson(b))};};
  return {temp,state,op,opPath,account,wrapping,materials,bindings,material,prepared,binding,custody,effect,resealOperation};
}
