import test from "node:test";
import assert from "node:assert/strict";
import { temporaryState } from "./helpers.js";
import { ChainAccountStore } from "../../src/chain-account-store.js";
import { StateStore } from "../../src/state.js";
import { AssetUsageLedger } from "../../src/asset-usage-ledger.js";
import { sealAssetPolicyRegistry } from "../../src/asset-policy-registry.js";
import { JupiterV1OwnerAdmission } from "../../src/swap/jupiter-solana/v1-admission.js";
import { createJupiterV1Runtime } from "../../src/swap/jupiter-solana/v1-runtime-factory.js";
import { JUPITER_V1_WHIRLPOOL_MECHANISM_PIN as OLD, JUPITER_V1_WHIRLPOOL_V2_MECHANISM_PIN as NEW, JUPITER_V1_WHIRLPOOL_V2_PROTOCOL_REGISTRY } from "../../src/swap/jupiter-solana/v1-pins.js";
import { SOLANA_USDC_MINT } from "../../src/swap/jupiter-solana/catalog.js";
import { AllowlistPolicyStore } from "../../src/allowlist-policy-store.js";
import { allowlistDecisionFingerprint } from "../../src/allowlist-policy-activation.js";
import { allowlistProfileHash } from "../../src/allowlist-policy-overlay.js";
import { SolanaRpc, SolanaRpcBudget } from "../../src/solana/rpc.js";
import { SolanaRpcPacer } from "../../src/solana/pacing.js";
import { syntheticV2Material, syntheticV2Simulation } from "../fixtures/jupiter-v1-whirlpool-v2/refusal-vectors.js";
import { guardJupiterV1WhirlpoolMaterial } from "../../src/swap/jupiter-solana/v1-guard.js";
import { fixture } from "../fixtures/jupiter-v1/material.js";
const profile="synthetic-v2-policy",payer=syntheticV2Material().payer,wrapping={async load(){return Buffer.alloc(32,77);},async create(){return Buffer.alloc(32,77);}};
function registry(pin=NEW,outputPin=pin){const now=new Date();return sealAssetPolicyRegistry({schemaVersion:"apn.asset-policy-registry.v1",registryVersion:"synthetic-v2.1",publishedAt:now.toISOString(),effectiveDate:now.toISOString().slice(0,10),effectiveAt:new Date(now.getTime()-1000).toISOString(),expiresAt:new Date(now.getTime()+3600000).toISOString(),chains:[{chain:NEW.chain,family:"solana",name:"Solana",assets:[{kind:"native",identifier:null,symbol:"SOL",decimals:9,rails:{direct:false,gasless:false,x402:false,bridge:false,swap:true},caps:{maximumPerTransferAtomic:"6000000",dailyLimitAtomic:"6000000"},mechanismPins:{swap:pin}},{kind:"token",identifier:SOLANA_USDC_MINT,symbol:"USDC",decimals:6,rails:{direct:false,gasless:false,x402:false,bridge:false,swap:true},caps:{maximumPerTransferAtomic:"500000",dailyLimitAtomic:"500000"},mechanismPins:{swap:outputPin}}]}]});}
test("SYNTHETIC owner admission selects exact equal finite policy mechanisms and rejects mixed/unknown",async t=>{const temp=await temporaryState();t.after(temp.cleanup);const store=new ChainAccountStore(temp.root,wrapping);await store.ensureLocal({profile,rail:"solana",create:async()=>({address:payer,seed:Buffer.alloc(32,9)})});let r=registry(),digest=r.policyDigest;const admission=new JupiterV1OwnerAdmission(store,async()=>({profile,registry:r,digest,revision:1,accounts:{solana:payer},activationDigest:"a".repeat(64),activatedAt:r.effectiveAt!}),new AssetUsageLedger(temp.root),()=>new Date());assert.equal((await admission.resolveRoute(profile,"1000000","115960",payer)).route.variant,47);r=registry(OLD);digest=r.policyDigest;assert.equal((await admission.resolveRoute(profile,"1000000","115960",payer)).route.variant,17);r=registry(OLD,NEW);digest=r.policyDigest;await assert.rejects(admission.resolveRoute(profile,"1000000","115960",payer));r=registry({...NEW,validationPolicyVersion:"9.9.9"});digest=r.policyDigest;await assert.rejects(admission.resolveRoute(profile,"1000000","115960",payer));});
async function pipeline(t:test.TestContext){
 const temp=await temporaryState();t.after(temp.cleanup);const state=new StateStore(temp.root),store=new ChainAccountStore(temp.root,wrapping);await store.ensureLocal({profile,rail:"solana",create:async()=>({address:payer,seed:Buffer.alloc(32,9)})});
 const now=new Date(),policy=new AllowlistPolicyStore(temp.root),staged=await policy.stage({profile,now,policy:{schemaVersion:"apn.allowlist-policy-file.v1",overlayVersion:"synthetic-v2.1",accounts:{solana:payer},effectiveAt:new Date(now.getTime()-1000).toISOString(),expiresAt:new Date(now.getTime()+3600000).toISOString(),admissions:[{chain:NEW.chain,kind:"native",rail:"swap",maximumPerTransferAtomic:"6000000",dailyLimitAtomic:"6000000",mechanism:NEW},{chain:NEW.chain,kind:"token",identifier:SOLANA_USDC_MINT,rail:"swap",maximumPerTransferAtomic:"500000",dailyLimitAtomic:"500000",mechanism:NEW}]}});
 const activation=await policy.appendDecision(profile,null,{status:"active",revision:staged.revision,stagedRecordDigest:staged.recordDigest,policyDigest:staged.registry.policyDigest,registry:staged.registry,approvalFingerprint:allowlistDecisionFingerprint({action:"activate",profileHash:allowlistProfileHash(profile),revision:staged.revision,stagedRecordDigest:staged.recordDigest,policyDigest:staged.registry.policyDigest,headEntryDigest:null}),decidedAt:now.toISOString()});
 const m=syntheticV2Material(),g=await guardJupiterV1WhirlpoolMaterial(m),sim=syntheticV2Simulation(g);let calls=0,http=0,secrets=0,sends=0,returnOld=false,clockMs=Date.now();
 const rpcFetch:typeof fetch=async(_url,init)=>{calls++;const body=JSON.parse(String(init?.body));const handle=async(q:any)=>{let result:unknown;const wire=(key:string,slice?:{offset:number;length:number})=>{const a=m.semanticAccounts.find(a=>a.address===key);if(a===undefined||a.existence==="absent")return null;const d=Buffer.from(a.dataBase64,"base64");return {owner:a.owner,lamports:Number(a.lamports),executable:a.executable,data:[(slice===undefined?d:d.subarray(slice.offset,slice.offset+slice.length)).toString("base64"),"base64"],space:d.length,rentEpoch:0};};
 switch(q.method){case"getGenesisHash":result=m.genesis;break;case"getMultipleAccounts":result={context:{slot:Number(m.accountSlot)},value:q.params[0].map((key:string)=>wire(key,q.params[1]?.dataSlice))};break;case"getAccountInfo":result={context:{slot:Number(m.accountSlot)},value:wire(q.params[0],q.params[1]?.dataSlice)};break;case"getLatestBlockhash":result={context:{slot:Number(m.accountSlot)},value:{blockhash:m.lifetime.blockhash,lastValidBlockHeight:Number(m.lifetime.lastValidBlockHeight)}};break;case"getFeeForMessage":result={context:{slot:Number(m.accountSlot)},value:6400};break;case"getBlockHeight":result=Number(m.lifetime.lastValidBlockHeight)-100;break;case"getMinimumBalanceForRentExemption":result=1488440;break;case"simulateTransaction":assert.equal(q.params[0],m.transactionBase64);result=sim;break;case"sendTransaction":sends++;throw Error("No TEST signing authorized in this unit");default:throw Error(`Unexpected TEST method ${q.method}`);}
 return {jsonrpc:"2.0",id:q.id,result};};const response=Array.isArray(body)?await Promise.all(body.map(handle)):await handle(body);
 return new Response(JSON.stringify(response),{headers:{"content-type":"application/json"}});
 };
 function runtime(stage:"quote"|"prepare"|"execute"|"observe",operationId?:string){return createJupiterV1Runtime({state,clock:{now:()=>new Date()},rpc:new SolanaRpc("https://example.com",rpcFetch,new SolanaRpcBudget({maxPhysicalRequests:64,minimumIntervalMs:750,now:()=>clockMs,wait:async ms=>{clockMs+=ms;}}),new SolanaRpcPacer(state,()=>clockMs,async ms=>{clockMs+=ms;})),wrappingSecret:{async load(){secrets++;throw Error("No TEST secret access in this unit");},async create(){throw Error();}},foreground:false,stage,...(operationId===undefined?{}:{operationId}),providerFetch:async url=>{http++;return new Response(JSON.stringify(String(url).includes("/quote?")?(returnOld?fixture().quoteResponse:m.quoteResponse):m.rawBuildResponse),{headers:{"content-type":"application/json"}});}});}
 return {m,runtime,get calls(){return calls;},get http(){return http;},get secrets(){return secrets;},get sends(){return sends;},oldQuote(){returnOld=true;},async revoke(){await policy.appendDecision(profile,activation.entryDigest,{status:"revoked",revision:staged.revision,stagedRecordDigest:staged.recordDigest,policyDigest:staged.registry.policyDigest,approvalFingerprint:allowlistDecisionFingerprint({action:"revoke",profileHash:allowlistProfileHash(profile),revision:staged.revision,stagedRecordDigest:staged.recordDigest,policyDigest:staged.registry.policyDigest,headEntryDigest:activation.entryDigest}),decidedAt:new Date().toISOString()});}};
}
const request={command:"swap.jupiter.quote" as const,profile,account:payer,recipient:payer,amountAtomic:"1000000",slippageBps:50,ownerSlippageCapBps:50};
test("SYNTHETIC canonical V2 runtime quotes and prepares with new registry, no custody/sign/send",async t=>{const f=await pipeline(t),rt=f.runtime("quote"),q=await rt.quote(request,new Date()) as {quoteHash:string};assert.ok(q.quoteHash);const before=f.calls;const op=await f.runtime("prepare").prepare({profile,quoteHash:q.quoteHash,idempotencyKey:"synthetic-v2"},new Date());assert.equal(f.calls,before);assert.equal(op.mechanismDigest,"c0ba30b8f7e47ce275c198599be046822dd5204740cc4985c27e0374041728b6");assert.equal(op.protocolRegistryDigest,JUPITER_V1_WHIRLPOOL_V2_PROTOCOL_REGISTRY.registryDigest);assert.equal(op.submissionMarker,null);await assert.rejects(f.runtime("execute",op.operationId).approve(op.operationId,new Date()),/foreground terminal/);assert.equal(f.secrets,0);assert.equal(f.sends,0);});
test("SYNTHETIC policy-selected new route refuses old provider quote before build and RPC",async t=>{const f=await pipeline(t);f.oldQuote();await assert.rejects(f.runtime("quote").quote(request,new Date()));assert.equal(f.http,1);assert.equal(f.calls,0);assert.equal(f.secrets,0);assert.equal(f.sends,0);});
test("SYNTHETIC revoked new policy refuses saved prepare before reserve/custody/network",async t=>{const f=await pipeline(t),q=await f.runtime("quote").quote(request,new Date()) as {quoteHash:string};await f.revoke();const before=f.calls;await assert.rejects(f.runtime("prepare").prepare({profile,quoteHash:q.quoteHash,idempotencyKey:"revoked"},new Date()));assert.equal(f.calls,before);assert.equal(f.secrets,0);assert.equal(f.sends,0);});
