import test from "node:test";
import { SolanaRpc } from "../../src/solana/rpc.js";
import assert from "node:assert/strict";
import { getBase58Decoder, getBase58Encoder, getTransactionDecoder, getTransactionEncoder, signatureBytes } from "@solana/kit";
import { fixture, mutate } from "../fixtures/jupiter-v1/material.js";
import { guardJupiterV1WhirlpoolMaterial, type JupiterV1GuardedMaterial } from "../../src/swap/jupiter-solana/v1-guard.js";
import { canonicalJupiterV1RpcJson, jupiterV1RpcResponseHash, proveJupiterV1Quote, snapshotFromJupiterV1QuoteProof, proveJupiterV1Simulation, validateFinalizedJupiterV1Receipt } from "../../src/swap/jupiter-solana/v1-proof.js";
import { simulation, receipt } from "../fixtures/jupiter-v1/scenarios.js";
import { TOKEN_PROGRAM, SOLANA_USDC_MINT } from "../../src/swap/jupiter-solana/catalog.js";
test("V1 exact unsigned simulation admits typed official extensions and proves both minima/rent",async()=>{const g=await guardJupiterV1WhirlpoolMaterial(fixture()),response=simulation(g);let called=false;const proof=await proveJupiterV1Simulation({async call(method,params){assert.equal(method,"simulateTransaction");assert.equal(params[0],g.material.transactionBase64);assert.equal((params[1] as any).sigVerify,false);assert.equal((params[1] as any).replaceRecentBlockhash,false);called=true;return response;}},g);assert.ok(called);assert.equal(proof.nativeSpendLamports,"1006400");assert.equal(proof.recipientOutputAtomic,"116130");});
for(const [name,fn] of Object.entries({"false CPI":(v:any)=>{v.value.innerInstructions[0].instructions[0].programIdIndex=0;},"native CPI input":(v:any)=>{const ix=v.value.innerInstructions[0].instructions[0],d=Buffer.from(getBase58Encoder().encode(ix.data));d.writeBigUInt64LE(1000001n,8);ix.data=getBase58Decoder().decode(d);},"native threshold/sqrt bytes":(v:any)=>{const ix=v.value.innerInstructions[0].instructions[0],d=Buffer.from(getBase58Encoder().encode(ix.data));d.fill(255,16,40);ix.data=getBase58Decoder().decode(d);},"output CPI vs delta":(v:any)=>{const ix=v.value.innerInstructions[0].instructions[2],d=Buffer.from(getBase58Encoder().encode(ix.data));d.writeBigUInt64LE(115550n,1);ix.data=getBase58Decoder().decode(d);},"pool lamport debit":(v:any,g:JupiterV1GuardedMaterial)=>{v.value.accounts[g.material.compiledAccounts.findIndex(a=>a.address===g.pool)].lamports--;},"unknown false extension":(v:any)=>{v.context.unknown=false;v.value.ownerSafetyVerified=false;},"payer identity":(v:any)=>{v.value.accounts[0].owner=TOKEN_PROGRAM;},"tick lamport debit":(v:any,g:JupiterV1GuardedMaterial)=>{v.value.accounts[g.material.compiledAccounts.findIndex(a=>a.address===g.nativeAccounts[7])].lamports--;},"double debit":(v:any)=>{v.value.accounts[0].lamports-=1000000;},"fee tip":(v:any)=>{v.value.accounts[0].lamports-=1;},"replacement blockhash":(v:any)=>{v.value.replacementBlockhash={blockhash:"fake",lastValidBlockHeight:1};},"delegate after":(v:any,g:JupiterV1GuardedMaterial)=>{const a=v.value.accounts[g.material.compiledAccounts.findIndex(a=>a.address===g.destinationTokenAccount)],d=Buffer.from(a.data[0],"base64");d.writeUInt32LE(1,72);a.data[0]=d.toString("base64");},"rent retained":(v:any,g:JupiterV1GuardedMaterial)=>{v.value.accounts[g.material.compiledAccounts.findIndex(a=>a.address===g.sourceTokenAccount)]={owner:TOKEN_PROGRAM,lamports:1488440,executable:false,data:["","base64"],space:0,rentEpoch:0};},"untyped extension":(v:any)=>{v.context.apiVersion=123;},"failed simulation":(v:any)=>{v.value.err={InstructionError:[5,"Custom"]};}}))test(`V1 proof rejects ${name}`,async()=>{const g=await guardJupiterV1WhirlpoolMaterial(fixture()),v=simulation(g);fn(v,g);await assert.rejects(proveJupiterV1Simulation({async call(){return v;}},g));});
test("V1 proof rejects changed guarded message before RPC",async()=>{const g=await guardJupiterV1WhirlpoolMaterial(fixture());await assert.rejects(proveJupiterV1Simulation({async call(){throw new Error("must not call");}},{...g,material:mutate(g.material,v=>{v.rawBuildResponse.setupInstructions[1].data="AgAAAEFCDwAAAAAA";})}));});
test("V1 finalized receipt binds signature/message/ALT and actual output",async()=>{const g=await guardJupiterV1WhirlpoolMaterial(fixture()),r=receipt(g),p=await validateFinalizedJupiterV1Receipt({async call(method){return method==="getSignatureStatuses"?r.status:r.response;}},g,{signature:r.signature});assert.equal(p.recipientOutputAtomic,"116130");assert.equal(p.nativeSpendLamports,"1006400");});
test("V1 finalized receipt rejects non-final status and loaded address substitution",async()=>{const g=await guardJupiterV1WhirlpoolMaterial(fixture());for(const kind of ["status","loaded"]){const r=receipt(g);if(kind==="status")r.status.value[0]!.confirmationStatus="confirmed";else r.response.meta.loadedAddresses.writable.reverse();await assert.rejects(validateFinalizedJupiterV1Receipt({async call(method){return method==="getSignatureStatuses"?r.status:r.response;}},g,{signature:r.signature}));}});

test("V1 opaque quote proof rejects forged/cloned snapshots and binds real producer output",async()=>{const material=fixture(),g=await guardJupiterV1WhirlpoolMaterial(material),input={profile:"fixture",account:material.payer,recipient:material.payer,amountAtomic:"1000000",slippageBps:50,now:new Date("2026-10-07T13:51:00.000Z")};const evidence=await proveJupiterV1Quote({async call(){return simulation(g);}},material,input),snapshot=snapshotFromJupiterV1QuoteProof(evidence,material,input);assert.equal(snapshot.providerResponseHash,material.materialDigest);assert.equal(snapshot.routeHash,g.admissionDigest);assert.equal(snapshot.simulation.requestHash.length,64);assert.throws(()=>snapshotFromJupiterV1QuoteProof(snapshot,material,input));assert.throws(()=>snapshotFromJupiterV1QuoteProof({...evidence},material,input));assert.throws(()=>snapshotFromJupiterV1QuoteProof(evidence,material,{...input,amountAtomic:"1000001"}));assert.throws(()=>snapshotFromJupiterV1QuoteProof(evidence,material,{...input,now:new Date(input.now.getTime()+1)}));});
for(const kind of ["pool","tick","vaultB","destination","unknownMeta","unknownCpi","unknownToken","outputCpi","nativeArgs"])test(`V1 receipt rejects ${kind} review regression`,async()=>{const g=await guardJupiterV1WhirlpoolMaterial(fixture()),r=receipt(g),keys=g.material.compiledAccounts.map(a=>a.address);if(["pool","tick","vaultB","destination"].includes(kind)){const key=kind==="pool"?g.pool:kind==="tick"?g.nativeAccounts[7]!:kind==="vaultB"?g.nativeAccounts[6]!:g.destinationTokenAccount;r.response.meta.postBalances[keys.indexOf(key)]!--;}else if(kind==="unknownMeta")(r.response.meta as any).ownerSafetyVerified=false;else if(kind==="unknownCpi")r.response.meta.innerInstructions[0].instructions[0].unverified=false;else if(kind==="unknownToken")(r.response.meta.postTokenBalances[0] as any).unverified=false;else{const ix=r.response.meta.innerInstructions[0].instructions[kind==="outputCpi"?2:0],d=Buffer.from(getBase58Encoder().encode(ix.data));if(kind==="outputCpi")d.writeBigUInt64LE(115550n,1);else d.fill(255,16,40);ix.data=getBase58Decoder().decode(d);}await assert.rejects(validateFinalizedJupiterV1Receipt({async call(method){return method==="getSignatureStatuses"?r.status:r.response;}},g,{signature:r.signature}));});

test("V1 RPC digest treats numeric integers and bigint identically without lossy conversion",()=>{assert.equal(canonicalJupiterV1RpcJson({slot:7,apiVersion:"3.1.8",nested:[0,1.5,null]}),canonicalJupiterV1RpcJson({slot:7n,apiVersion:"3.1.8",nested:[0n,1.5,null]}));assert.match(canonicalJupiterV1RpcJson({lamports:18446744073709551615n}),/18446744073709551615/);assert.notEqual(jupiterV1RpcResponseHash("test",{slot:7n}),jupiterV1RpcResponseHash("test",{slot:"7"}));assert.throws(()=>canonicalJupiterV1RpcJson({slot:Number.MAX_SAFE_INTEGER+1}));assert.throws(()=>canonicalJupiterV1RpcJson({slot:18446744073709551616n}));});
test("V1 genuine SolanaRpc fake HTTP bigint pipeline proves simulation, quote and receipt",async()=>{const material=fixture(),g=await guardJupiterV1WhirlpoolMaterial(material),sim=simulation(g),r=receipt(g);for(const rows of [r.response.meta.preTokenBalances,r.response.meta.postTokenBalances])for(const row of rows)row.uiTokenAmount.uiAmount=0 as any;let posts=0;const rpc=new SolanaRpc("https://rpc.example",(async(_url,init)=>{posts++;const req=JSON.parse(init!.body as string);const result=req.method==="simulateTransaction"?sim:req.method==="getSignatureStatuses"?r.status:r.response;return new Response(JSON.stringify({jsonrpc:"2.0",id:req.id,result}),{status:200,headers:{"content-type":"application/json"}});}) as typeof fetch);const transport=await rpc.call("simulateTransaction",[material.transactionBase64,{}]) as any;assert.equal(typeof transport.context.slot,"bigint");assert.equal(typeof transport.value.accounts[0].lamports,"bigint");assert.equal(typeof transport.value.innerInstructions[0].instructions[0].programIdIndex,"bigint");const proof=await proveJupiterV1Simulation(rpc,g),numeric=await proveJupiterV1Simulation({async call(){return sim;}},g);assert.equal(proof.resultHash,numeric.resultHash);const input={profile:"fixture",account:material.payer,recipient:material.payer,amountAtomic:"1000000",slippageBps:50,now:new Date("2026-10-07T13:51:00.000Z")},issued=await proveJupiterV1Quote(rpc,material,input),snapshot=snapshotFromJupiterV1QuoteProof(issued,material,input);assert.equal(snapshot.simulation.resultHash,proof.resultHash);const receiptProof=await validateFinalizedJupiterV1Receipt(rpc,g,{signature:r.signature}),numericReceipt=await validateFinalizedJupiterV1Receipt({async call(method){return method==="getSignatureStatuses"?r.status:r.response;}},g,{signature:r.signature});assert.equal(receiptProof.receiptHash,numericReceipt.receiptHash);assert.equal(receiptProof.recipientOutputAtomic,"116130");assert.equal(posts,5);});
