import test from "node:test";
import assert from "node:assert/strict";
import { getBase58Decoder, getBase58Encoder } from "@solana/kit";
import { syntheticV2Material, syntheticV2Simulation, syntheticV2Receipt } from "../fixtures/jupiter-v1-whirlpool-v2/refusal-vectors.js";
import { mutate } from "../fixtures/jupiter-v1/material.js";
import { guardJupiterV1WhirlpoolMaterial, type JupiterV1GuardedMaterial } from "../../src/swap/jupiter-solana/v1-guard.js";
import { proveJupiterV1Simulation, proveJupiterV1Quote, snapshotFromJupiterV1QuoteProof, validateFinalizedJupiterV1Receipt } from "../../src/swap/jupiter-solana/v1-proof.js";
import { decodeWhirlpoolV2TickArray } from "../../src/swap/jupiter-solana/v1-whirlpool-v2-accounts.js";
import { JUPITER_V1_MEMO_PROGRAM } from "../../src/swap/jupiter-solana/v1-pins.js";
const call=(v:any)=>({async call(){return v;}});
function ixBytes(v:any,index:number,fn:(d:Buffer)=>Buffer|void){const ix=v.value.innerInstructions[0].instructions[index],d=Buffer.from(getBase58Encoder().encode(ix.data)),out=fn(d)??d;ix.data=getBase58Decoder().decode(out);}
function changedAccount(v:any,g:JupiterV1GuardedMaterial,key:string,fn:(d:Buffer)=>void){const row=v.value.accounts[g.material.compiledAccounts.findIndex(a=>a.address===key)],d=Buffer.from(row.data[0],"base64");fn(d);row.data[0]=d.toString("base64");}
test("SYNTHETIC V2 typed model simulation and receipt satisfy exact parser contract; no live evidence",async()=>{const g=await guardJupiterV1WhirlpoolMaterial(syntheticV2Material()),p=await proveJupiterV1Simulation(call(syntheticV2Simulation(g)),g);assert.equal(p.recipientOutputAtomic,g.quotedOutputAtomic);const r=syntheticV2Receipt(g),receipt=await validateFinalizedJupiterV1Receipt({async call(method){return method==="getSignatureStatuses"?r.status:r.response;}},g,{signature:r.signature});assert.equal(receipt.recipientOutputAtomic,g.quotedOutputAtomic);});
const cases:Record<string,(v:any,g:JupiterV1GuardedMaterial)=>void>={
 "native threshold":v=>ixBytes(v,0,d=>{d[16]=1;}),"native sqrt":v=>ixBytes(v,0,d=>{d[24]=1;}),"native Some":v=>ixBytes(v,0,d=>{d[42]=1;}),"native wrong amount":v=>ixBytes(v,0,d=>{d.writeBigUInt64LE(1000001n,8);}),"native wrong discriminator":v=>ixBytes(v,0,d=>{d[0]=0;}),"native wrong direction":v=>ixBytes(v,0,d=>{d[41]=0;}),"native ExactOut":v=>ixBytes(v,0,d=>{d[40]=0;}),"native trailing":v=>ixBytes(v,0,d=>Buffer.concat([d,Buffer.from([0])])),"native stack":v=>{v.value.innerInstructions[0].instructions[0].stackHeight=3;},"native role order":v=>{v.value.innerInstructions[0].instructions[0].accounts.reverse();},
 "unchecked Transfer":v=>ixBytes(v,1,d=>{d[0]=3;return d.subarray(0,9);}),"input decimals":v=>ixBytes(v,1,d=>{d[9]=6;}),"output decimals":v=>ixBytes(v,2,d=>{d[9]=9;}),"output amount":v=>ixBytes(v,2,d=>{d.writeBigUInt64LE(1n,1);}),"input role order":v=>{v.value.innerInstructions[0].instructions[1].accounts.reverse();},"input authority":v=>{const i=v.value.innerInstructions[0].instructions;i[1].accounts[3]=i[2].accounts[3];},"input mint":v=>{const i=v.value.innerInstructions[0].instructions;i[1].accounts[1]=i[2].accounts[1];},"wrong token stack":v=>{v.value.innerInstructions[0].instructions[1].stackHeight=2;},"transfer before native":v=>{const i=v.value.innerInstructions[0].instructions;[i[0],i[1]]=[i[1],i[0]];},"output before input":v=>{const i=v.value.innerInstructions[0].instructions;[i[1],i[2]]=[i[2],i[1]];},"missing native":v=>{v.value.innerInstructions[0].instructions.shift();},"missing transfer":v=>{v.value.innerInstructions[0].instructions.pop();},"extra transfer":v=>{v.value.innerInstructions[0].instructions.push(v.value.innerInstructions[0].instructions[1]);},"extra native":v=>{v.value.innerInstructions[0].instructions.push(v.value.innerInstructions[0].instructions[0]);},"wrong group":v=>{v.value.innerInstructions[0].index=0;},"duplicate group":v=>{v.value.innerInstructions.push(v.value.innerInstructions[0]);},"Memo CPI":(v,g)=>{v.value.innerInstructions[0].instructions.push({programIdIndex:g.material.compiledAccounts.findIndex(a=>a.address===JUPITER_V1_MEMO_PROGRAM),accounts:[],data:"1",stackHeight:3});},"unknown self CPI roles":(v,g)=>{v.value.innerInstructions[0].instructions.push({programIdIndex:g.material.compiledAccounts.findIndex(a=>a.address===g.material.rawBuildResponse.swapInstruction.programId),accounts:[],data:"1",stackHeight:2});},
 "oracle constants":(v,g)=>changedAccount(v,g,g.namedRoles!.oracle,d=>{d[48]=31;}),"oracle reserved":(v,g)=>changedAccount(v,g,g.namedRoles!.oracle,d=>{d[110]=1;}),"oracle overflow":(v,g)=>changedAccount(v,g,g.namedRoles!.oracle,d=>{d.writeUInt32LE(880001,106);}),"pool output-side fee":(v,g)=>changedAccount(v,g,g.pool,d=>{d[93]=d[93]!^1;}),"pool static reward extension":(v,g)=>changedAccount(v,g,g.pool,d=>{d[333]=d[333]!^1;}),"pool static emission":(v,g)=>changedAccount(v,g,g.pool,d=>{d[365]=d[365]!^1;}),"dynamic liquidity":(v,g)=>changedAccount(v,g,g.namedRoles!.ticks[2],d=>{d[133]=d[133]!^1;}),"dynamic bitmap":(v,g)=>changedAccount(v,g,g.namedRoles!.ticks[2],d=>{d[44]=1;}),"dynamic tag":(v,g)=>changedAccount(v,g,g.namedRoles!.ticks[2],d=>{d[132]=0;}),"dynamic uninitialized reward":(v,g)=>changedAccount(v,g,g.namedRoles!.ticks[2],d=>{d[197]=1;}),"unrelated memo bytes":(v,g)=>changedAccount(v,g,JUPITER_V1_MEMO_PROGRAM,d=>{d[4]=d[4]!^1;}),"unrelated lamport":(v,g)=>{v.value.accounts[g.material.compiledAccounts.findIndex(a=>a.address===g.namedRoles!.oracle)].lamports--;},"low output":(v,g)=>changedAccount(v,g,g.destinationTokenAccount,d=>{d.writeBigUInt64LE(d.readBigUInt64LE(64)-10000n,64);}),"replacement blockhash":v=>{v.value.replacementBlockhash={blockhash:"changed",lastValidBlockHeight:1};},"fee null":v=>{v.value.fee=null;},"fee mismatch":v=>{v.value.fee=20001;},"compute excess":v=>{v.value.unitsConsumed=1400001;},"unknown field":v=>{v.value.syntheticSafety=true;},"signed simulation error":v=>{v.value.err={InstructionError:[5,"Custom"]};}
};
for(const [name,change] of Object.entries(cases))test(`SYNTHETIC V2 proof refuses ${name}`,async()=>{const g=await guardJupiterV1WhirlpoolMaterial(syntheticV2Material()),v=syntheticV2Simulation(g);change(v,g);let afterProofEffects=0;await assert.rejects(async()=>{await proveJupiterV1Simulation(call(v),g);afterProofEffects++;});assert.equal(afterProofEffects,0);});
for(let mask=0;mask<8;mask++)test(`SYNTHETIC all reward combination ${mask} permits only initialized reward growth`,async()=>{
 const m=mutate(syntheticV2Material(),v=>{const a=v.semanticAccounts.find((a:any)=>a.address===v.quoteResponse.routePlan[0].swapInfo.ammKey),d=Buffer.from(a.dataBase64,"base64");for(let r=0;r<3;r++)if(mask&(1<<r))d[269+128*r]=1;a.dataBase64=d.toString("base64");}),g=await guardJupiterV1WhirlpoolMaterial(m),sim=syntheticV2Simulation(g);
 changedAccount(sim,g,g.pool,d=>{for(const {offset} of [{offset:49,length:16},{offset:85,length:8},{offset:165,length:16},{offset:261,length:8}])d[offset]=d[offset]!^1;for(let r=0;r<3;r++)if(mask&(1<<r))d[381+128*r]=1;});
 for(const key of g.namedRoles!.ticks){const a=m.semanticAccounts.find(a=>a.address===key)!,state=decodeWhirlpoolV2TickArray(a);let c=state.kind==="fixed"?12:60;for(const tick of state.ticks){const cursor=c;if(tick.initialized)changedAccount(sim,g,key,d=>{d[cursor+33]=d[cursor+33]!^1;d[cursor+49]=d[cursor+49]!^1;for(let r=0;r<3;r++)if(mask&(1<<r))d[cursor+65+16*r]=d[cursor+65+16*r]!^1;});c+=state.kind==="dynamic"&&!tick.initialized?1:113;}}
 changedAccount(sim,g,g.namedRoles!.oracle,d=>{d.writeBigUInt64LE(d.readBigUInt64LE(82)+1n,82);d.writeUInt32LE(880000,106);});await proveJupiterV1Simulation(call(sim),g);
 for(let r=0;r<3;r++){const bad=syntheticV2Simulation(g);changedAccount(bad,g,g.namedRoles!.ticks[2],d=>{d[197+16*r]=1;});if(mask&(1<<r))await proveJupiterV1Simulation(call(bad),g);else await assert.rejects(proveJupiterV1Simulation(call(bad),g));const badPool=syntheticV2Simulation(g);changedAccount(badPool,g,g.pool,d=>{d[381+128*r]=1;});if(mask&(1<<r))await proveJupiterV1Simulation(call(badPool),g);else await assert.rejects(proveJupiterV1Simulation(call(badPool),g));}
});
test("SYNTHETIC V2 opaque producer proof cannot be fabricated or cloned",async()=>{const m=syntheticV2Material(),g=await guardJupiterV1WhirlpoolMaterial(m),input={profile:"synthetic-model",account:m.payer,recipient:m.payer,amountAtomic:"1000000",slippageBps:50,now:new Date("2026-10-07T15:48:00Z")};assert.throws(()=>snapshotFromJupiterV1QuoteProof({},m,input));const p=await proveJupiterV1Quote(call(syntheticV2Simulation(g)),m,input);assert.ok(snapshotFromJupiterV1QuoteProof(p,m,input));assert.throws(()=>snapshotFromJupiterV1QuoteProof({...p},m,input));assert.throws(()=>snapshotFromJupiterV1QuoteProof(p,m,{...input,account:g.pool}));});
for(const name of ["mint","owner","decimals","program","duplicate","lamport","signature","loaded","native-threshold"])test(`SYNTHETIC V2 receipt refuses ${name}`,async()=>{const g=await guardJupiterV1WhirlpoolMaterial(syntheticV2Material()),r=syntheticV2Receipt(g),row=r.response.meta.postTokenBalances[1];if(name==="mint")row.mint=g.namedRoles!.mintB;else if(name==="owner")row.owner=g.payer;else if(name==="decimals")row.uiTokenAmount.decimals=6;else if(name==="program")row.programId=JUPITER_V1_MEMO_PROGRAM;else if(name==="duplicate")r.response.meta.postTokenBalances.push(row);else if(name==="lamport")r.response.meta.postBalances[g.material.compiledAccounts.findIndex(a=>a.address===g.namedRoles!.oracle)]--;else if(name==="signature")r.signature="1".repeat(88);else if(name==="loaded")r.response.meta.loadedAddresses.writable.reverse();else{const ix=r.response.meta.innerInstructions[0].instructions[0],d=Buffer.from(getBase58Encoder().encode(ix.data));d[16]=1;ix.data=getBase58Decoder().decode(d);}await assert.rejects(validateFinalizedJupiterV1Receipt({async call(method){return method==="getSignatureStatuses"?r.status:r.response;}},g,{signature:r.signature}));});
