import test from "node:test";
import assert from "node:assert/strict";
import { chmod, mkdir, readFile, readdir, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson, domainHash, hashObject, sha256 } from "../../src/canonical.js";
import { sealAssetPolicyRegistry } from "../../src/asset-policy-registry.js";
import type { ActiveAssetPolicy } from "../../src/allowlist-active-policy.js";
import { AssetUsageLedger } from "../../src/asset-usage-ledger.js";
import { createSwapQuote } from "../../src/swap/quote.js";
import { newSwapOperation } from "../../src/swap/model.js";
import { transitionSwapOperation } from "../../src/swap/transitions.js";
import { SwapOperationRepository } from "../../src/swap/repository.js";
import { swapMechanismDigest } from "../../src/swap/pin.js";
import { HISTORICAL_JUPITER_IDS, HISTORICAL_JUPITER_OWNER_PROFILE, HISTORICAL_JUPITER_ACCOUNT_BINDING, HISTORICAL_JUPITER_PAYER } from "../../src/swap/jupiter-solana/historical-pins.js";
import { SOLANA_MAINNET_GENESIS, SOLANA_USDC_MINT } from "../../src/swap/jupiter-solana/catalog.js";
import { JUPITER_V1_OLD_ROUTE, JUPITER_V1_WHIRLPOOL_4H_ROUTE } from "../../src/swap/jupiter-solana/v1-route-config.js";
import { calculateHistoricalRetirementPolicy } from "../../src/swap/jupiter-solana/historical-retirement-policy.js";
import { HISTORICAL_RETIREMENT_IDENTITY as identity, HISTORICAL_RETIREMENT_NAMESPACE as namespace, HISTORICAL_RETIREMENT_SCHEMA,
 historicalRetirementBucketHash, sealHistoricalRetirementRecord, validateHistoricalRetirementRecord, type HistoricalRetirementRecord } from "../../src/swap/jupiter-solana/historical-retirement-record.js";
import { historicalRetirementRootSnapshot, JupiterHistoricalRetirementReader } from "../../src/swap/jupiter-solana/historical-retirement-reader.js";
import { temporaryState } from "./helpers.js";
const at=new Date("2026-10-10T12:00:00.000Z"), H=(s:string)=>s.repeat(64), blockhash="1".repeat(32);
// Public DTO fixtures only: no encrypted wallet, genuine owner ceremony, signer or financial authority.
function policy(perOp="6000000",daily="30000000",pin=JUPITER_V1_OLD_ROUTE.mechanismPin):ActiveAssetPolicy{
 const registry=sealAssetPolicyRegistry({schemaVersion:"apn.asset-policy-registry.v1",registryVersion:"test-retirement.1",publishedAt:"2026-10-09T00:00:00.000Z",effectiveDate:"2026-10-09",effectiveAt:"2026-10-09T00:00:00.000Z",expiresAt:"2026-10-12T00:00:00.000Z",chains:[{chain:identity.chain,family:"solana",name:"Solana",assets:[
 {kind:"native",identifier:null,symbol:"SOL",decimals:9,rails:{direct:false,gasless:false,x402:false,bridge:false,swap:true},caps:{maximumPerTransferAtomic:perOp,dailyLimitAtomic:daily},mechanismPins:{swap:pin}},
 {kind:"token",identifier:SOLANA_USDC_MINT,symbol:"USDC",decimals:6,rails:{direct:false,gasless:false,x402:false,bridge:false,swap:true},caps:{maximumPerTransferAtomic:"500000",dailyLimitAtomic:"500000"},mechanismPins:{swap:pin}}]}]});
 return {profile:"solana-local",registry,digest:registry.policyDigest,revision:1,accounts:{solana:HISTORICAL_JUPITER_PAYER},activationDigest:H("a"),activatedAt:"2026-10-09T00:00:00.000Z"};
}
async function fixture(root:string,index=0){
 const active=policy(),ledger=new AssetUsageLedger(root),id=HISTORICAL_JUPITER_IDS[index]!,idempotencyHash=H(String(index+1));
 const q=createSwapQuote({profile:"solana-local",account:identity.account,recipient:identity.account,sourceAsset:{...identity.asset,chain:identity.chain},destinationAsset:{chain:identity.chain,kind:"token",identifier:SOLANA_USDC_MINT},inputAmountAtomic:"1000000",expectedOutputAtomic:"100000",minimumOutputAtomic:"99500",slippageBps:50,effectiveAt:"2026-10-09T00:00:00.000Z",expiresAt:"2026-10-09T00:02:00.000Z",providerResponseHash:H("b"),routeHash:H("c"),unsignedTransactionPayloadHash:H("d"),simulation:{requestHash:H("e"),resultHash:H("f"),success:true,blockNumber:"100",blockHash:`0x${H("1")}`,headBlockNumber:"100",maxHeadDrift:0,gasEstimate:"1000"}});
 let op=newSwapOperation({operationId:id,idempotencyHash,quote:q,policyDigest:active.digest,policyVersion:active.registry.registryVersion,protocolRegistryDigest:JUPITER_V1_OLD_ROUTE.protocolRegistry.registryDigest,protocolRegistryVersion:JUPITER_V1_OLD_ROUTE.protocolRegistry.registryVersion,mechanismDigest:swapMechanismDigest(JUPITER_V1_OLD_ROUTE.mechanismPin),approvalCapAtomic:"0",now:new Date("2026-10-09T00:00:01.000Z")});
 const old=new Date("2026-10-09T00:00:02.000Z");op=transitionSwapOperation(op,"prepared",{},old);op=transitionSwapOperation(op,"awaiting_approval",{},old);
 const lease=await ledger.reserve({...identity,registry:active.registry,rail:"swap",amountAtomic:"1000000",idempotencyKey:`swap-${idempotencyHash}`,now:old});op=transitionSwapOperation(op,"reserved",{usageLease:lease},old);
 const markerBody={operationId:id,operationIntegrityHash:op.integrityHash,unsignedTransactionPayloadHash:q.unsignedTransactionPayloadHash,markedAt:old.toISOString()};
 op=transitionSwapOperation(op,"submitting",{submissionMarker:{operationIntegrityHash:markerBody.operationIntegrityHash,unsignedTransactionPayloadHash:markerBody.unsignedTransactionPayloadHash,markedAt:markerBody.markedAt,markerHash:domainHash("apn.swap-submission-marker.v1",canonicalJson(markerBody))}},old);
 const unknown=await ledger.transition({...identity,reservationId:lease.reservationId,policyDigest:lease.policyDigest,state:"unknown_finality",now:old});op=transitionSwapOperation(op,"unknown_finality",{usageLease:unknown},old);await new SwapOperationRepository(root).create(op);
 assert.equal(op.ownerProfileHash,HISTORICAL_JUPITER_OWNER_PROFILE);
 const path=join(root,"asset-usage",historicalRetirementBucketHash(),`${unknown.reservationId}.json`),bytes=await readFile(path);
 const authentication={schemaVersion:"apn.jupiter-historical-authentication.v1" as const,operationId:id,operationIntegrityHash:op.integrityHash,rootBinding:hashObject({root}),ownerProfileHash:op.ownerProfileHash,accountBindingHash:HISTORICAL_JUPITER_ACCOUNT_BINDING,payer:identity.account,policyDigest:op.policyDigest,activationDigest:H("a"),originalBindingHash:H("b"),originalMaterialDigest:H("c"),freshMaterialDigest:H("d"),markerHash:op.submissionMarker!.markerHash,principalLamports:"1000000",maximumNativeExpenseLamports:"6000000",freshMaximumNativeExpenseLamports:"6000000",networkFeeLamports:"6400",tokenAccountRentLamports:"1488440",genesis:SOLANA_MAINNET_GENESIS,blockhash,lastValidBlockHeight:"300",signature:"1".repeat(88),rawPayloadHash:H("9"),messageHash:H("8"),freshBlockhash:blockhash,freshLastValidBlockHeight:"300",heightBinding:"authenticated_material_not_signed_message" as const,originalQuoteRpcLifetime:{source:"configured_mainnet_rpc_before_quote_freeze" as const,rpcOriginHash:H("7"),contextSlot:"120",minimumContextSlot:"100",blockhash,lastValidBlockHeight:"300"},lifetimeProvenance:"configured_mainnet_rpc_before_quote_freeze" as const,retainedClaimEvidence:{kind:"retained_send_claim_present" as const,claimHash:H("6"),signedMarkerSnapshotHash:H("5")},ordinaryRecentBlockhash:true as const,authenticatedAt:at.toISOString(),authenticationExpiresAt:"2026-10-10T12:01:00.000Z"};
 const proofBody={schemaVersion:"apn.jupiter-canonical-future-invalidity.v1" as const,scope:"blockhash_future_invalidity_only" as const,outcome:"future_invalidity_witness" as const,inputHash:H("4"),transactionHash:authentication.rawPayloadHash,messageHash:authentication.messageHash,signatureHash:sha256(authentication.signature),blockhash,quoteContextSlot:"120",searchedStartSlot:"56",birth:{slot:"100",blockHeight:"200",blockhash},finalizedAnchor:{slot:"400",blockHeight:"400",blockhash:"2".repeat(32)},processingAge:{documentedMaximumProcessingAge:150 as const,requiredConservativeFinalizedHeight:"352"},quoteLastValidBlockHeight:"300",providers:[{originHash:H("2"),finalizedSlot:"400",finalizedBlockHeight:"400",isBlockhashValid:false as const,signatureStatusObservation:"not_reported" as const,readCount:20},{originHash:H("3"),finalizedSlot:"400",finalizedBlockHeight:"400",isBlockhashValid:false as const,signatureStatusObservation:"not_reported" as const,readCount:20}]};
 const usage=await ledger.usage(identity,at),record=sealHistoricalRetirementRecord({schemaVersion:HISTORICAL_RETIREMENT_SCHEMA,kind:"retired_unknown",operationId:id,ownerProfileHash:op.ownerProfileHash,rootSnapshotHash:await historicalRetirementRootSnapshot(root),bucketHash:historicalRetirementBucketHash(),originalOperation:op,originalReservationRawHash:sha256(bytes),authentication,canonicalProof:{...proofBody,resultHash:hashObject(proofBody)},currentPolicy:{registry:active.registry,activationDigest:active.activationDigest,revision:active.revision,activatedAt:active.activatedAt},policyAdmission:calculateHistoricalRetirementPolicy(active,id,usage.amountAtomic,"0",q.minimumOutputAtomic,at),accountingAt:at.toISOString(),conservativeTotalAtomic:"6000000",additionalAdmissionAtomic:"5000000",historicalOutcome:"unknown",transactionMayHaveBeenSubmitted:true,actualNativeFeeAtomic:null,effectAt:null});
 return {record,ledger,op,path,bytes,active};
}
async function saveFixture(root:string,r:HistoricalRetirementRecord){await mkdir(join(root,namespace),{mode:0o700});await writeFile(join(root,namespace,`${r.operationId}.json`),canonicalJson(r)+"\n",{mode:0o600});}
function reseal(v:any){const {recordHash,...body}=v;return {...body,recordHash:hashObject(body)};}

test("HELPER policy admits full6M and delta5M against usage including original hold",()=>{const a=calculateHistoricalRetirementPolicy(policy("6000000","6000000"),HISTORICAL_JUPITER_IDS[0],"1000000","0","99500",at);assert.equal(a.resultingNativeUsageAtomic,"6000000");assert.equal(a.additionalAdmissionAtomic,"5000000");assert.equal("authority" in a,false);});
test("HELPER policy refuses5M per-operation limit even though delta fits",()=>assert.throws(()=>calculateHistoricalRetirementPolicy(policy("5000000","6000000"),HISTORICAL_JUPITER_IDS[0],"1000000","0","99500",at)));
test("HELPER policy daily calculation includes oldhold instead of subtracting it",()=>assert.throws(()=>calculateHistoricalRetirementPolicy(policy("6000000","6000000"),HISTORICAL_JUPITER_IDS[0],"1000001","0","99500",at)));
for(const kind of ["missingpolicy","foreignprofile","foreignpayer","wrongroute","expired","zeroownhold","foreignID"]){test(`HELPER policy rejects ${kind}`,()=>{const a:any=policy();let u="1000000",id:string=HISTORICAL_JUPITER_IDS[0],when=at;if(kind==="foreignprofile")a.profile="other";if(kind==="foreignpayer")a.accounts.solana="1".repeat(32);if(kind==="wrongroute")Object.assign(a,policy("6000000","30000000",JUPITER_V1_WHIRLPOOL_4H_ROUTE.mechanismPin));if(kind==="expired")when=new Date("2026-10-12T00:00:00.000Z");if(kind==="zeroownhold")u="0";if(kind==="foreignID")id=H("f");assert.throws(()=>calculateHistoricalRetirementPolicy(kind==="missingpolicy"?null:a,id,u,"0","99500",when));});}

test("HELPER central usage replaces hold with6M across all readers and preserves original bytes",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);await saveFixture(tmp.root,f.record);for(const read of [()=>f.ledger.usage(identity,at),()=>f.ledger.usageReadOnly(identity,at),async()=>(await f.ledger.usageWithReservation(identity,f.op.usageLease!.reservationId,at)).snapshot])assert.equal((await read()).amountAtomic,"6000000");assert.deepEqual(await readFile(f.path),f.bytes);assert.equal((await f.ledger.load(identity,f.op.usageLease!.reservationId))!.effectAt,null);assert.equal((await new JupiterHistoricalRetirementReader(tmp.root).forBucket(identity,[f.op.usageLease!])).length,1);});
test("HELPER retirement6M current UTCday and zero carried hold on all later days",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);await saveFixture(tmp.root,f.record);assert.equal((await f.ledger.usage(identity,new Date("2026-10-10T23:59:59.999Z"))).amountAtomic,"6000000");for(const when of ["2026-10-11T00:00:00.000Z","2026-10-12T12:00:00.000Z"])assert.equal((await f.ledger.usage(identity,new Date(when))).amountAtomic,"0");await assert.rejects(f.ledger.usage(identity,new Date("2026-10-09T23:59:59.999Z")));assert.deepEqual(await readFile(f.path),f.bytes);});
test("HELPER three separate records aggregate18M with total15M delta",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);await mkdir(join(tmp.root,namespace),{recursive:true,mode:0o700});const fixtures=[];for(let i=0;i<3;i++)fixtures.push(await fixture(tmp.root,i));for(const f of fixtures){const usage=await f.ledger.usage(identity,at),{recordHash,...body}=f.record,r=sealHistoricalRetirementRecord({...body,policyAdmission:calculateHistoricalRetirementPolicy(f.active,f.op.operationId,usage.amountAtomic,"0",f.op.quote.minimumOutputAtomic,at)});await writeFile(join(tmp.root,namespace,`${r.operationId}.json`),canonicalJson(r)+"\n",{mode:0o600});}const f=fixtures[0]!;assert.equal((await f.ledger.usage(identity,at)).amountAtomic,"18000000");assert.equal((await f!.ledger.usage(identity,new Date("2026-10-11T00:00:00.000Z"))).amountAtomic,"0");});
test("HELPER new reserve cannot undercount record-first prefix without journal or receipt",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);await saveFixture(tmp.root,f.record);await assert.rejects(f.ledger.reserve({...identity,registry:policy("6000000","6000000").registry,rail:"swap",amountAtomic:"1",idempotencyKey:"helper-over-cap-record-first",now:at}));assert.deepEqual(await readdir(join(tmp.root,namespace)),[`${f.op.operationId}.json`]);assert.deepEqual(await readFile(f.path),f.bytes);});
test("HELPER read-only snapshot creates no missing retirement namespace",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);const before=await readdir(tmp.root);assert.equal((await f.ledger.usageReadOnly(identity,at)).amountAtomic,"1000000");assert.deepEqual(await readdir(tmp.root),before);});
for(const kind of ["recordhash","root","bucket","op","payer","oldrow","cap","freshcap","authdeadline","canonicalnonnull","canonicalage","canonicalorigins","policycap","policyusage","unknownfee","extrafield"]){test(`HELPER strict codec rejects ${kind}`,async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);const r:any=structuredClone(f.record);if(kind==="recordhash")r.recordHash=H("0");if(kind==="root")r.rootSnapshotHash="bad";if(kind==="bucket")r.bucketHash=H("0");if(kind==="op")r.operationId=H("0");if(kind==="payer")r.authentication.payer="1".repeat(32);if(kind==="oldrow")r.originalOperation.usageLease.amountAtomic="6000000";if(kind==="cap")r.conservativeTotalAtomic="5000000";if(kind==="freshcap")r.authentication.freshMaximumNativeExpenseLamports="5000000";if(kind==="authdeadline")r.accountingAt=r.authentication.authenticationExpiresAt;if(kind==="canonicalnonnull"){r.canonicalProof.providers[0].signatureStatusObservation="reported";const {resultHash,...body}=r.canonicalProof;r.canonicalProof.resultHash=hashObject(body);}if(kind==="canonicalage"){r.canonicalProof.providers[0].finalizedBlockHeight="351";const {resultHash,...body}=r.canonicalProof;r.canonicalProof.resultHash=hashObject(body);}if(kind==="canonicalorigins"){r.canonicalProof.providers[1].originHash=r.canonicalProof.providers[0].originHash;const {resultHash,...body}=r.canonicalProof;r.canonicalProof.resultHash=hashObject(body);}if(kind==="policycap"){r.currentPolicy.registry=policy("5000000").registry;}if(kind==="policyusage")r.policyAdmission.resultingNativeUsageAtomic="5000000";if(kind==="unknownfee")r.actualNativeFeeAtomic="0";if(kind==="extrafield")r.authority=true;assert.throws(()=>validateHistoricalRetirementRecord(kind==="recordhash"?r:reseal(r)));});}
for(const kind of ["rawrowchanged","operationchanged","rootrecreated","wrongrootcopied","foreignfile","symlinkrecord"]){test(`HELPER owned loader rejects ${kind}`,async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);await saveFixture(tmp.root,f.record);if(kind==="rawrowchanged")await writeFile(f.path,canonicalJson(f.op.usageLease),{mode:0o600});if(kind==="operationchanged"){const path=join(tmp.root,"swap-operations",f.op.ownerProfileHash,`${f.op.operationId}.json`);const {integrityHash,...body}=f.op;await writeFile(path,canonicalJson({...body,updatedAt:"2026-10-09T00:00:03.000Z",integrityHash:domainHash("apn.swap-operation.v1",canonicalJson({...body,updatedAt:"2026-10-09T00:00:03.000Z"}))}),{mode:0o600});}if(kind==="rootrecreated"){await rename(tmp.root,`${tmp.root}-old`);await mkdir(tmp.root,{mode:0o700});const {cp,rm}=await import("node:fs/promises");await cp(`${tmp.root}-old`,tmp.root,{recursive:true});t.after(()=>rm(`${tmp.root}-old`,{recursive:true,force:true}));}if(kind==="wrongrootcopied"){const r=reseal({...f.record,authentication:{...f.record.authentication,rootBinding:H("0")}});await writeFile(join(tmp.root,namespace,`${f.op.operationId}.json`),canonicalJson(r),{mode:0o600});}if(kind==="foreignfile")await writeFile(join(tmp.root,namespace,`${H("f")}.json`),canonicalJson(f.record),{mode:0o600});if(kind==="symlinkrecord"){const {symlink,unlink}=await import("node:fs/promises");const path=join(tmp.root,namespace,`${f.op.operationId}.json`);await rename(path,join(tmp.root,"helper-symlink-target.json"));await symlink(join(tmp.root,"helper-symlink-target.json"),path);}await assert.rejects(f.ledger.usage(identity,at));});}

for(const kind of ["claimabsentother","missingcanonical","birthwindow","authover60","fakefinality"]){test(`HELPER strict record rejects ${kind}`,async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);const r:any=structuredClone(f.record);if(kind==="claimabsentother")r.authentication.retainedClaimEvidence={kind:"retained_send_claim_absent",observation:"current_observation",submissionHistory:"unknown",transactionMayHaveBeenSubmitted:true,absenceSnapshotHash:H("a"),signedMarkerSnapshotHash:H("b")};if(kind==="missingcanonical")r.canonicalProof=null;if(kind==="birthwindow"){r.canonicalProof.searchedStartSlot="55";const {resultHash,...body}=r.canonicalProof;r.canonicalProof.resultHash=hashObject(body);}if(kind==="authover60")r.authentication.authenticationExpiresAt="2026-10-10T12:01:00.001Z";if(kind==="fakefinality")r.historicalOutcome="finalized";assert.throws(()=>validateHistoricalRetirementRecord(reseal(r)));});}
test("HELPER canonical age uses both current provider heights with a separately reanchored earlier block",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);const r:any=structuredClone(f.record);r.canonicalProof.finalizedAnchor.blockHeight="350";const {resultHash,...body}=r.canonicalProof;r.canonicalProof.resultHash=hashObject(body);assert.equal(validateHistoricalRetirementRecord(reseal(r)).canonicalProof.finalizedAnchor.blockHeight,"350");});
test("HELPER repeated restart reads do not rewrite record or original row",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);await saveFixture(tmp.root,f.record);const path=join(tmp.root,namespace,`${f.op.operationId}.json`),before=await readFile(path);for(let i=0;i<2;i++)assert.equal((await new AssetUsageLedger(tmp.root).usage(identity,at)).amountAtomic,"6000000");assert.deepEqual(await readFile(path),before);assert.deepEqual(await readFile(f.path),f.bytes);});

test("HELPER record rejects current authority deadline beyond policy TTL",async t=>{const tmp=await temporaryState();t.after(tmp.cleanup);const f=await fixture(tmp.root);const r:any=structuredClone(f.record),old=r.currentPolicy.registry;const {policyDigest,...body}=old;r.currentPolicy.registry=sealAssetPolicyRegistry({...body,expiresAt:"2026-10-10T12:00:30.000Z"});r.policyAdmission=calculateHistoricalRetirementPolicy({...f.active,registry:r.currentPolicy.registry,digest:r.currentPolicy.registry.policyDigest},f.op.operationId,"1000000","0",f.op.quote.minimumOutputAtomic,at);assert.throws(()=>validateHistoricalRetirementRecord(reseal(r)));});
