/** Synthetic Mega vectors; no signatures, funding or merchant requests. */
import assert from "node:assert/strict";
import test from "node:test";
import { sha256 } from "../../src/canonical.js";
import { StateStore } from "../../src/state.js";
import { OperationService } from "../../src/operation-service.js";
import { MEGA_FUNDING, inspectMegaFundingQuote, inspectMegaDelivery, megaJson } from "../../src/lifi/mega-gaszip-contract.js";
import { MegaFundingJournal, sealMegaFunding, type MegaFundingRecord } from "../../src/lifi/mega-gaszip-journal.js";
import { MegaFundingService } from "../../src/lifi/mega-gaszip-service.js";
import { proveMegaDelivery, readMegaFundingPlan, type MegaRpcPort } from "../../src/lifi/mega-gaszip-rpc.js";
import { temporaryState } from "./helpers.js";
import type { Hex } from "viem";
const hash=(digit:string)=>`0x${digit.repeat(64)}` as Hex;
const h=(n:bigint)=>`0x${n.toString(16)}`;
const OWNER=MEGA_FUNDING.owner,SIGNER="0x2222222222222222222222222222222222222222",OUTPUT="9897959742538",SOURCE=hash("1"),DEST=hash("2"),BLOCK=hash("3"),PREVIOUS=hash("4");
const body=(now:number)=>`{"calldata":"0x010202","expires":${Math.floor(now/1000)+60},"quotes":[{"chain":4326,"decimals":18,"expected":${OUTPUT},"expectedNative":${OUTPUT},"gas":60000000000,"speed":10.0,"usd":0.0241}]}`;
const provider=()=>({deposit:{block:"100",chain:"8453",hash:SOURCE,log:"0",sender:OWNER,shorts:["514"],status:"CONFIRMED",time:"1",to:OWNER,usd:0.0241,value:"10000000000000"},txs:[{chain:"4326",hash:DEST,nonce:"7",refund:false,cancelled:false,signer:SIGNER,status:"CONFIRMED",time:"1",to:OWNER,usd:0.0241,value:OUTPUT}]});
function record():MegaFundingRecord{return sealMegaFunding({schemaVersion:"apn.mega-gaszip-operation.v1",operationId:"a".repeat(64),profileHash:sha256("profile\0default"),idempotencyHash:"b".repeat(64),requestHash:"c".repeat(64),profile:"default",owner:{profile:"default",profileHash:sha256("profile\0default"),address:OWNER,walletBindingHash:"d".repeat(64),walletCreatedAt:"2026-10-09T00:00:00.000Z"},providerBinding:{providerId:"local",accountBindingHash:"d".repeat(64),capabilityHash:"e".repeat(64),revision:1},amountAtomic:"10000000000000",minimumOutputAtomic:"8000000000000",maximumFeeAtomic:"1000000000000",quoteDigest:"f".repeat(64),quoteExpectedAtomic:OUTPUT,expiresAt:"2026-10-09T00:01:00.000Z",policyDigest:"1".repeat(64),policyRevision:1,plan:{blockHash:BLOCK,nonce:"0",gas:"23382",maxFee:"11000000",tip:"1000000",l1FeeUpper:"0",operatorFeeUpper:"0",feeUpper:"257202000000"},state:"prepared",terminal:false,rawTransaction:null,transactionHash:null,submissionAttempts:0,usageReservationId:null,outcomeDigest:null,sourceProof:null,destinationProof:null});}
test("Mega quote is exact, lossless and independent of Sei route and floor",()=>{const now=Date.now(),q=inspectMegaFundingQuote(megaJson(body(now)),now);assert.equal(q.expectedAtomic,OUTPUT);assert.equal(MEGA_FUNDING.mechanism.reference,"v2-direct-base-mega-self-010202.1");for(const text of [body(now).replace('010202','0100f6'),body(now).replace('4326','1329'),body(now).replaceAll(OUTPUT,'7999999999999')])assert.throws(()=>inspectMegaFundingQuote(megaJson(text),now));assert.throws(()=>inspectMegaFundingQuote(megaJson(body(now)),now+60000));});
test("Mega provider correlation refuses wrong chain, owner, source, short, amount and duplicate outbound",()=>{assert.equal(inspectMegaDelivery(provider(),SOURCE,OWNER,"10000000000000","100")?.amount,OUTPUT);const cases=[{...provider(),deposit:{...provider().deposit,shorts:["246"]}},{...provider(),deposit:{...provider().deposit,sender:SIGNER}},{...provider(),deposit:{...provider().deposit,value:"9999999999999"}},{...provider(),txs:[{...provider().txs[0],chain:"1329"}]},{...provider(),txs:[...provider().txs,...provider().txs]},{...provider(),txs:[{...provider().txs[0],refund:true}]}];for(const v of cases)assert.throws(()=>inspectMegaDelivery(v,SOURCE,OWNER,"10000000000000","100"));assert.throws(()=>inspectMegaDelivery(provider(),DEST,OWNER,"10000000000000"));assert.throws(()=>inspectMegaDelivery(provider(),SOURCE,SIGNER,"10000000000000"));assert.equal(inspectMegaDelivery({...provider(),deposit:{...provider().deposit,status:"PENDING"}},SOURCE,OWNER,"10000000000000"),null);});
class Destination implements MegaRpcPort{wrongChain=false;wrongAmount=false;wrongBlock=false;unsafe=false;wrongDelta=false;async call(method:string,params:readonly unknown[]):Promise<unknown>{if(method==="eth_chainId")return h(this.wrongChain?1329n:4326n);if(method==="eth_getBlockByNumber")return {number:h(this.unsafe && params[0]==="safe"?99n:100n),hash:params[0]===h(99n)?PREVIOUS:this.wrongBlock?SOURCE:BLOCK};if(method==="eth_getCode")return "0x";if(method==="eth_getBalance")return (params[1] as {blockHash:string}).blockHash===PREVIOUS?"0x0":h(BigInt(OUTPUT)+(this.wrongDelta?1n:0n));const common={hash:DEST,transactionHash:DEST,from:SIGNER,to:OWNER,blockHash:BLOCK,blockNumber:h(100n)};if(method==="eth_getTransactionByHash")return {...common,chainId:h(4326n),input:"0x",value:h(BigInt(OUTPUT)+(this.wrongAmount?1n:0n)),nonce:h(7n)};if(method==="eth_getTransactionReceipt")return {...common,status:"0x1"};throw Error(method);}}
test("independent Mega receipt requires exact native effect, canonical safe inclusion and exact credit",async()=>{const d=inspectMegaDelivery(provider(),SOURCE,OWNER,"10000000000000")!;assert.equal((await proveMegaDelivery(new Destination(),OWNER,d))?.amount,OUTPUT);for(const key of ["wrongChain","wrongAmount","wrongBlock","wrongDelta"] as const){const rpc=new Destination();rpc[key]=true;await assert.rejects(proveMegaDelivery(rpc,OWNER,d));}const pending=new Destination();pending.unsafe=true;assert.equal(await proveMegaDelivery(pending,OWNER,d),null);});
test("fixed Mega owner and principal cannot be rebound in a sealed journal",()=>{const r=record();for(const next of [{...r,profile:"other"},{...r,owner:{...r.owner,address:SIGNER}},{...r,amountAtomic:"9999999999999"},{...r,minimumOutputAtomic:"7999999999999"}])assert.throws(()=>sealMegaFunding(next as MegaFundingRecord));});
test("Mega durable conflict blocks same Base owner including other rails, but not a Mega nonce",async(t)=>{const temp=await temporaryState();t.after(temp.cleanup);const state=new StateStore(temp.root);await state.initialize();await new MegaFundingJournal(temp.root).saveLocked(record(),true);const ops=new OperationService(state);await assert.rejects(ops.assertEvmAccountAvailable(record().profileHash,8453,OWNER),{code:"APN_OPERATION_BLOCKED"});await ops.assertEvmAccountAvailable(record().profileHash,4326,OWNER);assert.equal((await ops.required(record().operationId)).kind,"mega_gaszip");assert.equal((await ops.findIdempotency(record().idempotencyHash))?.kind,"mega_gaszip");});
test("unsigned expiry retires only without a signing claim; status is observe-only after signing",async(t)=>{const temp=await temporaryState();t.after(temp.cleanup);const state=new StateStore(temp.root);await state.initialize();const journal=new MegaFundingJournal(temp.root),r=record();await journal.saveLocked(r,true);const wrapping={load:async()=>{throw Error("no signing allowed");},create:async()=>{throw Error("no custody creation");}};const service=new MegaFundingService(state,wrapping,{}, {now:()=>Date.parse("2026-10-09T00:02:00.000Z")});await journal.claimSigningLocked(r);await assert.rejects(service.status(r.operationId),/effect_marker_blocks_retirement/u);await assert.rejects(journal.claimSigningLocked(r));await journal.saveLocked(sealMegaFunding({...r,state:"signing_started"}));assert.equal((await service.approve(r.operationId) as MegaFundingRecord).state,"signing_started");assert.equal((await service.status(r.operationId) as MegaFundingRecord).state,"signing_started");});
test("Base fee planning keeps frozen signed affordability and refuses wrong network",async()=>{const rpc: MegaRpcPort={call:async(m)=>m==="eth_chainId"?h(8453n):m==="eth_getBlockByNumber"?{hash:BLOCK,number:h(100n),baseFeePerGas:h(1_000_000n)}:m==="eth_getCode"?"0x":m==="eth_getBalance"?h(10_100_000_000_000n):m==="eth_getTransactionCount"?"0x0":m==="eth_estimateGas"?h(21256n):m==="eth_call"?`0x${"0".repeat(64)}`:null};assert.ok(await readMegaFundingPlan(rpc,OWNER,"10000000000000","1000000000000"));await assert.rejects(readMegaFundingPlan(rpc,OWNER,"10000000000000","1000000000000","257202000000"),/source_balance_or_fee_cap/u);await assert.rejects(readMegaFundingPlan({call:async()=>h(4326n)},OWNER,"10000000000000","1000000000000"),/source_chain/u);});
