import test from "node:test";
import assert from "node:assert/strict";
import { readFile,writeFile,unlink,mkdir,cp } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson,hashObject } from "../../src/canonical.js";
import { ApnError } from "../../src/errors.js";
import { AssetUsageLedger,assetUsageReservationId } from "../../src/asset-usage-ledger.js";
import { MerchantService } from "../../src/x402-merchant/service.js";
import { MerchantRepository } from "../../src/x402-merchant/repository.js";
import { MerchantClaims } from "../../src/x402-merchant/claims.js";
import { MerchantRetirementClaims } from "../../src/x402-merchant/retirement-claims.js";
import { merchantMove,validateMerchant, type MerchantOperation } from "../../src/x402-merchant/model.js";
import { merchantReceipt } from "../../src/x402-merchant/rpc.js";
import { merchantUsageIdentity,merchantNativeUsageIdentity,merchantUsageKey,merchantNativeUsageKey } from "../../src/x402-merchant/owner.js";
import { appendMerchantFailure } from "../../src/x402-merchant/failure.js";
import { executeMerchantCli } from "../../src/x402-merchant/cli.js";
import { BridgeHttps } from "../../src/lifi/https.js";
import { bindArgv } from "../../src/command-binder.js";
import { temporaryState } from "./helpers.js";
import { merchantFixture,TX_HASH } from "./merchant-x402-fixtures.js";
async function setup(t:test.TestContext){const temp=await temporaryState();t.after(temp.cleanup);return merchantFixture(temp.root);}
async function headroom(f:Awaited<ReturnType<typeof merchantFixture>>,reserve="2000000000000") {return f.service.prepare({profile:"default",maximumNativeFee:"100000000000000",nativeFeeReserveWei:reserve,idempotencyKey:"merchant-headroom-test"});}
async function fenced(f:Awaited<ReturnType<typeof merchantFixture>>,o:MerchantOperation){
 const s=new MerchantService(f.state,{rpc:f.rpc,http:f.http,now:f.now,approve:async()=>{f.rpc.operation=o;},custody:{sign:async()=>{throw new ApnError("APN_OPERATION_BLOCKED","arbitrary secret should never persist",{reason:"merchant_fee_witness_expired"});},verify:async()=>TX_HASH,seal:async()=>{throw Error("never seal");}}});return s.approve(o.operationId);
}
async function file(f:Awaited<ReturnType<typeof merchantFixture>>,path:string,value:unknown){await mkdir(join(f.state.root,path.slice(0,path.lastIndexOf('/'))),{recursive:true,mode:0o700});await writeFile(join(f.state.root,path),canonicalJson(value)+'\n',{mode:0o600});}
const reason=(r:string)=>(e:unknown)=>(e as ApnError).details?.reason===r;
test("normal preparation freezes declared2T reserve independently of original quote; post-confirm L1 rise fits",async t=>{const f=await setup(t),o=await headroom(f);assert.equal(o.effectBinding?.nativeAmountAtomic,"2000000000000");assert.notEqual(o.feeContext!.admissionEstimatedUpper,o.effectBinding!.nativeAmountAtomic);f.onApprove(async()=>{f.rpc.l1Upper=10000n;});const done=await f.service.approve(o.operationId);assert.equal(done.state,"delivered");assert.equal(done.envelope.nativeFeeReserveWei,"2000000000000");assert.equal(f.rpc.sends,1);assert.deepEqual(done.envelope,o.envelope);});
for(const reserve of ["1","100000000000001","0","01"])test(`reserve ${reserve} refuses before any journal/sign`,async t=>{const f=await setup(t);await assert.rejects(headroom(f,reserve));assert.equal(f.signs(),0);assert.equal((await f.service.records.listAllOperations()).length,0);});
test("declared reserve must fit full native balance",async t=>{const f=await setup(t),v=f.rpc.value.bind(f.rpc);f.rpc.value=async(m,p)=>m==="eth_getBalance"?"0x100000":v(m,p);await assert.rejects(headroom(f));assert.equal(f.rpc.sends,0);});
test("original2T reserve survives safe L1 decrease; overreserve/nonce/gas cannot sign",async t=>{for(const mode of ["lower","over","nonce","gas"]){const f=await setup(t),o=await headroom(f);f.onApprove(async()=>{if(mode==="lower")f.rpc.l1Upper=1n;if(mode==="over")f.rpc.l1Upper=2000000000000n;if(mode==="nonce")f.rpc.nonce="0x1";if(mode==="gas"){const v=f.rpc.value.bind(f.rpc);f.rpc.value=async(m,p)=>m==="eth_estimateGas"?"0x100000":v(m,p);}});if(mode==="lower")assert.equal((await f.service.approve(o.operationId)).state,"delivered");else{await assert.rejects(f.service.approve(o.operationId));assert.equal(f.signs(),0);assert.equal(f.rpc.sends,0);}}});
test("successful native usage consumes canonical FULL actual fee and releases unused reserve only",async t=>{const f=await setup(t),o=await headroom(f),done=await f.service.approve(o.operationId),ledger=new AssetUsageLedger(f.state.root);const n=await ledger.load(merchantNativeUsageIdentity,assetUsageReservationId(merchantNativeUsageIdentity,merchantNativeUsageKey(o.operationId))),token=await ledger.load(merchantUsageIdentity,assetUsageReservationId(merchantUsageIdentity,merchantUsageKey(o.operationId)));assert.equal(n?.state,"finalized");assert.equal(n?.amountAtomic,"2000000000000");assert.equal(n?.consumedAtomic,done.receipt!.networkFeeWei);assert.equal(n?.merchantNativeActualFee?.receiptHash,hashObject(done.receipt));assert.equal((await ledger.usage(merchantNativeUsageIdentity,f.now())).amountAtomic,done.receipt!.networkFeeWei);assert.equal(token?.amountAtomic,"1000000000000000");assert.equal(token?.consumedAtomic,undefined);assert.equal((await ledger.usage(merchantUsageIdentity,f.now())).amountAtomic,"1000000000000000");});
test("serialized/forged receipt cannot grant successful fee partial-consumption; generic transition refuses",async t=>{const f=await setup(t),o=await headroom(f),done=await f.service.approve(o.operationId),ledger=new AssetUsageLedger(f.state.root);await assert.rejects(ledger.settleMerchantNativeActualFee(o,structuredClone(done.receipt!),f.now()),reason("merchant_native_actual_fee_authority_required"));await assert.rejects(ledger.transition({...merchantNativeUsageIdentity,reservationId:assetUsageReservationId(merchantNativeUsageIdentity,merchantNativeUsageKey(o.operationId)),policyDigest:o.policy.digest,state:"finalized",outcomeDigest:"a".repeat(64),consumedAtomic:"1",now:f.now()}));});
test("wrong intent and abovehold actual fee cannot mint a native settlement",async t=>{const f=await setup(t),o=await headroom(f);f.rpc.operation=o;const attempted=merchantMove(merchantMove(o,"signing_started",f.now().toISOString(),{signingAttempts:1}),"submission_started",f.now().toISOString(),{submissionAttempts:1,txHash:TX_HASH});const r=await merchantReceipt(f.rpc,attempted),ledger=new AssetUsageLedger(f.state.root);await assert.rejects(ledger.settleMerchantNativeActualFee({...attempted,profile:"foreign"},r!,f.now()));f.rpc.l1Actual=2000000000000n;await assert.rejects(merchantReceipt(f.rpc,attempted));});
test("future failure retains only allowlisted reason+phase; historical unclassified message remains hidden",async t=>{const f=await setup(t),o=await headroom(f),u=await fenced(f,o);assert.equal(u.failures?.[0]?.reason,"merchant_fee_witness_expired");assert.equal(u.failures?.[0]?.phase,"custody");assert.equal(JSON.stringify(u).includes('arbitrary secret'),false);assert.equal(u.submissionAttempts,0);const hidden=appendMerchantFailure(o,new Error("private key secret raw 0x123"),"pre_custody_fee",f.now().toISOString());assert.equal(hidden.failures![0]!.reason,"merchant_failure_unclassified");assert.equal(JSON.stringify(hidden).includes("private key"),false);});
test("retire permanent claim precedes both real ledger releases; remains unpaid and idempotent",async t=>{const f=await setup(t),o=await headroom(f),u=await fenced(f,o);f.advance(300001);const retired=await f.service.retireUnsent(o.operationId);assert.equal(retired.state,"retired_unsent");assert.equal(retired.terminal,true);assert.equal(retired.receipt,null);assert.equal(retired.txHash,null);assert.ok(retired.retirementDigest);assert.equal((await new MerchantRetirementClaims(f.state.root).find(retired))?.claimDigest,retired.retirementDigest);assert.deepEqual(retired.events.slice(0,u.events.length),u.events);const ledger=new AssetUsageLedger(f.state.root);assert.equal((await ledger.usage(merchantNativeUsageIdentity,f.now())).amountAtomic,"0");assert.equal((await ledger.usage(merchantUsageIdentity,f.now())).amountAtomic,"0");assert.deepEqual(await f.service.retireUnsent(o.operationId),retired);assert.equal(f.rpc.sends,0);assert.equal(f.headers.length,0);await assert.rejects(f.service.approve(o.operationId));});
for(const mode of ["active","send","material","nonce","native","token","claimcorrupt","claimmissing","policy","owner"] as const)test(`retirement ${mode} refuses; no hold release or broadcast`,async t=>{const f=await setup(t),o=await headroom(f),u=await fenced(f,o);if(mode!=="active")f.advance(300001);if(mode==="send")await file(f,`merchant-effect-claims/${o.operationId}.send.json`,{});if(mode==="material")await file(f,`merchant-material/${o.operationId}.json`,{});if(mode==="claimmissing")await unlink(join(f.state.root,`merchant-effect-claims/${o.operationId}.sign.json`));if(mode==="claimcorrupt")await file(f,`merchant-effect-claims/${o.operationId}.sign.json`,{});if(mode==="nonce")f.rpc.nonce="0x1";if(mode==="policy")f.advance(3600001);if(mode==="owner")await unlink(join(f.state.root,`wallets/${o.profileHash}/wallet.json`)).catch(()=>{});if(mode==="native"||mode==="token"){const v=f.rpc.value.bind(f.rpc);let hits=0;f.rpc.value=async(m,p)=>{if(mode==="native"&&m==="eth_getBalance"&&typeof p[1]==="object")return ++hits===1?"0x100000":"0x100001";if(mode==="token"&&m==="eth_call"&&String((p[0] as any).data).startsWith("0x70a08231")&&typeof p[1]==="object")return `0x${(++hits===1?10n:11n).toString(16).padStart(64,'0')}`;return v(m,p);};}await assert.rejects(f.service.retireUnsent(o.operationId));const ledger=new AssetUsageLedger(f.state.root);assert.equal((await ledger.usage(merchantUsageIdentity,f.now())).amountAtomic,"1000000000000000");assert.equal(f.rpc.sends,0);assert.equal((await f.service.status(o.operationId)).state,u.state);});
test("retirement tombstone and SIGN survive restored journal and permanently block signing",async t=>{const f=await setup(t),o=await headroom(f);await fenced(f,o);f.advance(300001);await f.service.retireUnsent(o.operationId);await file(f,`merchant-x402/${o.operationId}.json`,o);await assert.rejects(new MerchantClaims(f.state.root).assertUnused(o),reason("merchant_retirement_permanent_fence"));await assert.rejects(f.service.approve(o.operationId));assert.equal(f.rpc.sends,0);});
test("retired terminal journal without matching tombstone never clears normal availability",async t=>{const f=await setup(t),o=await headroom(f);await fenced(f,o);f.advance(300001);await f.service.retireUnsent(o.operationId);await unlink(join(f.state.root,`merchant-retirement/${o.operationId}.json`));await assert.rejects(new MerchantRepository(f.state.root).findOperation(o.operationId),reason("merchant_retirement_tombstone_required"));});
test("production normal retire CLI with fake network uses real records, policy locks and ledger; no Keychain/sign",async t=>{const f=await setup(t),o=await headroom(f);await fenced(f,o);f.advance(300001);let physical=0,keyLoads=0;t.mock.method(BridgeHttps.prototype,"request",async(_url:string,_verb:"GET"|"POST",body?:string)=>{physical++;const req=JSON.parse(body!);const rows=Array.isArray(req)?req:[req],result=await Promise.all(rows.map(async(x:any)=>({jsonrpc:"2.0",id:x.id,result:await f.rpc.value(x.method,x.params)})));return {status:200,body:JSON.stringify(Array.isArray(req)?result:result[0])};});const bound=bindArgv(["x402","merchant","retire-unsent","--operation",o.operationId]);const result=await executeMerchantCli(bound,{clock:{now:f.now},wrappingSecret:{load:async()=>{keyLoads++;return null;},create:async()=>{throw Error('no key');}}},f.state.root);assert.equal(result.ok,true);assert.equal((result.data as any).state,"retired_unsent");assert.equal((result.data as any).paymentFinalized,false);assert.equal((result.data as any).retirementReceipt.payment,false);assert.equal(keyLoads,0);assert.ok(physical>0&&physical<=64);assert.equal(f.rpc.sends,0);});

test("SEND appearing after permanent tombstone still blocks BOTH hold releases",async t=>{const f=await setup(t),o=await headroom(f);await fenced(f,o);f.advance(300001);const original=MerchantRetirementClaims.prototype.mark;t.mock.method(MerchantRetirementClaims.prototype,"mark",async function(this:MerchantRetirementClaims,...args:Parameters<typeof original>){const c=await original.apply(this,args);await file(f,`merchant-effect-claims/${o.operationId}.send.json`,{});return c;});await assert.rejects(f.service.retireUnsent(o.operationId),reason("merchant_retirement_exposed"));const ledger=new AssetUsageLedger(f.state.root);assert.equal((await ledger.usage(merchantUsageIdentity,f.now())).amountAtomic,"1000000000000000");assert.equal((await ledger.usage(merchantNativeUsageIdentity,f.now())).amountAtomic,"2000000000000");assert.equal((await f.service.status(o.operationId)).state,"unknown_finality");});
test("active controller owner/custody lock prevents retirement until its foreground scope exits",async t=>{const f=await setup(t),o=await headroom(f);let enter!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>enter=r),held=new Promise<void>(r=>release=r);const s=new MerchantService(f.state,{rpc:f.rpc,http:f.http,now:f.now,approve:async()=>{f.rpc.operation=o;},custody:{sign:async()=>{enter();await held;throw Error('fake signer abort');},verify:async()=>TX_HASH,seal:async()=>{}}});const approval=s.approve(o.operationId);await entered;f.advance(300001);let retired=false;const attempt=f.service.retireUnsent(o.operationId).then(x=>{retired=true;return x;});await new Promise(r=>setTimeout(r,100));assert.equal(retired,false);assert.equal(await readFile(join(f.state.root,`merchant-retirement/${o.operationId}.json`),'utf8').catch(()=>null),null);release();await approval;assert.equal((await attempt).state,"retired_unsent");assert.equal(f.rpc.sends,0);});
test("normal production prepare and foreground approve freeze2T then late private wallet fee guard blocks before key access",async t=>{
 const f=await setup(t);f.advance(Date.now()-f.now().getTime());await f.activate();let physical=0,keyReads=0,keychainLoads=0,terminalText="",phrase="",ttyOpens=0;
 t.mock.method(BridgeHttps.prototype,"request",async(_url:string,_verb:"GET"|"POST",body?:string)=>{physical++;const req=JSON.parse(body!);const rows=Array.isArray(req)?req:[req],result=await Promise.all(rows.map(async(x:any)=>{assert.notEqual(x.method,"eth_sendRawTransaction");return {jsonrpc:"2.0",id:x.id,result:await f.rpc.value(x.method,x.params)};}));return {status:200,body:JSON.stringify(Array.isArray(req)?result:result[0])};});
 const {EncryptedWalletStore}=await import("../../src/encrypted-wallet-store.js");t.mock.method(EncryptedWalletStore.prototype,"describe",async()=>{f.rpc.l1Upper=2000000000000n;const o=(await f.service.records.listAllOperations())[0]!;return {identity:{profile:o.profile,address:o.custody.walletAddress,chainId:8453,createdAt:o.custody.walletCreatedAt,bindingHash:o.custody.walletBindingHash},secret:{get privateKey(){keyReads++;throw Error('private key must not be read');}}} as never;});t.mock.method(EncryptedWalletStore.prototype,"clear",()=>{});
 const options={clock:{now:f.now},http:f.http,wrappingSecret:{load:async()=>{keychainLoads++;return null;},create:async()=>{throw Error('no key creation');}},merchantTtyOptions:{isTerminal:()=>true,openTerminal:async()=>{ttyOpens++;return {fd:1,write:async(text:string)=>{terminalText+=text;phrase=/Type ([a-f0-9]{8})/.exec(text)![1]!;},read:async function*(){yield Buffer.from(phrase+'\n');},close:async()=>{}};}}};
 const prepared=await executeMerchantCli(bindArgv(["x402","merchant","prepare","--profile","default","--max-native-fee-wei","100000000000000","--native-fee-reserve-wei","2000000000000","--idempotency-key","production-headroom-normal"]),options,f.state.root);assert.equal(prepared.ok,true);const id=(prepared.data as any).operationId;
 const result=await executeMerchantCli(bindArgv(["x402","merchant","approve","--operation",id]),options,f.state.root);assert.equal(result.ok,true);const o=await f.service.status(id);assert.equal(o.state,"unknown_finality");assert.equal(o.submissionAttempts,0);assert.equal(o.failures?.[0]?.phase,"custody");assert.equal(o.failures?.[0]?.reason,"merchant_full_fee_admission_changed");assert.match(terminalText,/full owner hold: 2000000000000/);assert.equal(ttyOpens,1);assert.equal(keyReads,0);assert.equal(keychainLoads,0);assert.equal(f.rpc.sends,0);assert.ok(physical<=64);
});

test("fresh canonical branded receipt cannot settle copied hold in a different ledger root",async t=>{const f=await setup(t),o=await headroom(f),done=await f.service.approve(o.operationId),r=await merchantReceipt(f.rpc,done),other=await setup(t);await cp(join(f.state.root,'asset-usage'),join(other.state.root,'asset-usage'),{recursive:true});await assert.rejects(new AssetUsageLedger(other.state.root).settleMerchantNativeActualFee(done,r!,f.now()),/this ledger root durable paid operation/);assert.equal((await new AssetUsageLedger(f.state.root).usage(merchantNativeUsageIdentity,f.now())).amountAtomic,done.receipt!.networkFeeWei);});
test("fresh branded receipt still requires exact tx claim and submission count",async t=>{const f=await setup(t),o=await headroom(f),done=await f.service.approve(o.operationId),r=await merchantReceipt(f.rpc,done),ledger=new AssetUsageLedger(f.state.root);const {sealMerchant}=await import('../../src/x402-merchant/model.js');for(const changed of [{...done,txHash:`0x${'a'.repeat(64)}`},{...done,submissionAttempts:0}]){await assert.rejects(ledger.settleMerchantNativeActualFee(changed as MerchantOperation,r!,f.now()));}await assert.rejects(ledger.settleMerchantNativeActualFee(o,r!,f.now()));});

test("normal observer recovers paid-journal/native-ledger crash across advancing finalized heads idempotently",async t=>{
 const f=await setup(t),o=await headroom(f),original=AssetUsageLedger.prototype.settleMerchantNativeActualFee;let fail=true;t.mock.method(AssetUsageLedger.prototype,"settleMerchantNativeActualFee",async function(this:AssetUsageLedger,...args:Parameters<typeof original>){if(fail){fail=false;throw Error('simulated crash after durable paid receipt');}return original.apply(this,args);});
 await assert.rejects(f.service.approve(o.operationId),/simulated crash/);const paid=await f.service.status(o.operationId);assert.equal(paid.state,"payment_finalized");const originalReceipt=canonicalJson(paid.receipt),v=f.rpc.value.bind(f.rpc),newHash=`0x${'e'.repeat(64)}`;
 f.rpc.value=async(m,p)=>{const row=await v(m,p);if(m==='eth_getBlockByNumber'&&(p[0]==='finalized'||p[0]==='0x11'))return {...row as Record<string,unknown>,number:'0x11',hash:newHash,parentHash:paid.receipt!.blockHash};return row;};
 const closed=await f.service.observe(o.operationId);assert.equal(closed.state,'payment_finalized');assert.equal(canonicalJson(closed.receipt),originalReceipt);assert.equal(closed.canonicalObservations!.at(-1)!.currentAnchors!.finalizedNumber,'17');const ledger=new AssetUsageLedger(f.state.root),id=assetUsageReservationId(merchantNativeUsageIdentity,merchantNativeUsageKey(o.operationId)),r=await ledger.load(merchantNativeUsageIdentity,id);assert.equal(r?.state,'finalized');assert.equal(r?.merchantNativeActualFee?.receiptHash,hashObject(paid.receipt));assert.equal(r?.consumedAtomic,paid.receipt!.networkFeeWei);await f.service.observe(o.operationId);assert.equal((await ledger.load(merchantNativeUsageIdentity,id))?.outcomeDigest,r?.outcomeDigest);assert.equal(f.signs(),1);assert.equal(f.rpc.sends,1);assert.equal(canonicalJson((await f.service.status(o.operationId)).receipt),originalReceipt);
});
