import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";
import test from "node:test";
import { canonicalJson, hashObject } from "../../src/canonical.js";
import { merchantPolicyAsset, MERCHANT_MECHANISM, MERCHANT_CHAIN, MERCHANT_TOKEN } from "../../src/x402-merchant/pins.js";
import { merchantChallenge, checkMerchantChallenge, merchantProof } from "../../src/x402-merchant/protocol.js";
import { merchantMove } from "../../src/x402-merchant/model.js";
import { merchantReceipt } from "../../src/x402-merchant/rpc.js";
import { OperationService } from "../../src/operation-service.js";
import { verifyMerchantRaw } from "../../src/x402-merchant/custody.js";
import { bindArgv, bindMcpInput } from "../../src/command-binder.js";
import { MCP_TOOLS } from "../../src/mcp-projection.js";
import { temporaryState, RAW_TRANSACTION } from "./helpers.js";
import { merchantFixture, challenge, observation, TX_HASH } from "./merchant-x402-fixtures.js";
async function setup(t:test.TestContext){const temp=await temporaryState();t.after(temp.cleanup);return merchantFixture(temp.root);}
test("actual challenge shape preserves full frozen resource/accepted and canonical v2 tx proof",()=>{
 const f=merchantChallenge(observation(new Date()));assert.deepEqual(f.challenge,challenge);
 assert.deepEqual(JSON.parse(Buffer.from(merchantProof(f,TX_HASH),"base64").toString()),{x402Version:2,payload:{txHash:TX_HASH},resource:challenge.resource,accepted:challenge.accepts[0]});
});
for(const mutate of [(c:any)=>{c.resource.url="https://example.com";},(c:any)=>{c.accepts[0].network="eip155:1";},(c:any)=>{c.accepts[0].amount="1";},(c:any)=>{c.accepts[0].extra.name="MegaUSD";},(c:any)=>{c.accepts.push(c.accepts[0]);},(c:any)=>{c.extensions.unknown={};}])test("finite challenge refuses drift/ambiguity",()=>{const c=structuredClone(challenge);mutate(c);assert.throws(()=>checkMerchantChallenge(c));});
test("only exact new x402 pin resolves the supplement",()=>{const i={chain:MERCHANT_CHAIN,kind:"token",identifier:MERCHANT_TOKEN,rail:"x402",mechanism:MERCHANT_MECHANISM};assert.ok(merchantPolicyAsset(i));for(const rail of ["direct","gasless","bridge","swap"])assert.equal(merchantPolicyAsset({...i,rail}),undefined);assert.equal(merchantPolicyAsset({...i,mechanism:{provider:"eip3009",reference:"anything"}}),undefined);});
test("one sign/send, finalized exact Transfer, HTTP 200 price and saved headers prove delivery",async t=>{const f=await setup(t),o=await f.prepare(),done=await f.service.approve(o.operationId);assert.equal(done.state,"delivered");assert.equal(f.signs(),1);assert.equal(f.seals(),1);assert.equal(f.rpc.sends,1);assert.equal(done.receipt?.finality,"finalized");assert.equal(done.deliveryAttempts.at(-1)?.result?.bitcoin!==undefined,true);assert.equal(done.deliveryAttempts.at(-1)?.headers?.[1]?.[0],"payment-response");assert.deepEqual(await f.prepare(),done);await assert.rejects(f.service.approve(o.operationId));await f.service.observe(o.operationId,true);assert.equal(f.rpc.sends,1);assert.equal(f.headers.length,1);});
test("lost send response is held; observer proves payment without resending",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.lost=true;const held=await f.service.approve(o.operationId);assert.equal(held.state,"unknown_finality");assert.equal(held.submissionAttempts,1);assert.equal(f.headers.length,0);const paid=await f.service.observe(o.operationId);assert.equal(paid.state,"payment_finalized");assert.equal(f.rpc.sends,1);assert.equal(f.signs(),1);await f.service.observe(o.operationId,true);assert.equal(f.headers.length,1);assert.equal(f.rpc.sends,1);});
test("delivery loss stays paid/delivery_unknown; explicit observer retries identical header only",async t=>{const f=await setup(t),o=await f.prepare();f.failDelivery();const held=await f.service.approve(o.operationId);assert.equal(held.state,"delivery_unknown");assert.equal(held.receipt?.status,"success");await f.service.observe(o.operationId);assert.equal(f.headers.length,1);f.repairDelivery();const done=await f.service.observe(o.operationId,true);assert.equal(done.state,"delivered");assert.equal(f.headers[0],f.headers[1]);assert.equal(f.rpc.sends,1);assert.equal(f.signs(),1);});
for(const mode of ["nonce","code","policy","expired"] as const)test(`changed ${mode} during confirmation refuses with zero custody/effects`,async t=>{const f=await setup(t),o=await f.prepare();f.onApprove(async()=>{if(mode==="nonce")f.rpc.nonce="0x1";if(mode==="code")f.rpc.badCode=true;if(mode==="policy")await f.activate();if(mode==="expired")f.advance(300001);});await assert.rejects(f.service.approve(o.operationId));assert.equal(f.signs(),0);assert.equal(f.rpc.sends,0);});
test("queued dispatch expiry leaves permanent marker and zero actual broadcast",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.queued=()=>f.advance(300001);const held=await f.service.approve(o.operationId);assert.equal(held.submissionAttempts,1);assert.equal(held.state,"unknown_finality");assert.equal(f.rpc.sends,0);await assert.rejects(f.service.approve(o.operationId));assert.equal(f.signs(),1);});
test("unfinalized receipt cannot disclose proof or claim merchant delivery",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.finality=false;const held=await f.service.approve(o.operationId);assert.equal(held.receipt,null);assert.equal(f.headers.length,0);f.rpc.finality=true;assert.equal((await f.service.observe(o.operationId,true)).state,"delivered");});
test("wrong transfer and reorg remain unknown; no manufactured settlement",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.receiptOverride=r=>{r.logs=[];};const held=await f.service.approve(o.operationId);assert.equal(held.receipt,null);assert.equal(f.headers.length,0);f.rpc.receiptOverride=undefined;f.rpc.reorg=true;await assert.rejects(merchantReceipt(f.rpc,held));});
test("global conflict/idempotency and append journal cannot lose charged unknown or reuse operation",async t=>{const f=await setup(t),o=await f.prepare(),operations=new OperationService(f.state);assert.equal((await operations.required(o.operationId)).kind,"merchant_x402");await assert.rejects(operations.assertEvmAccountAvailable(o.profileHash,4326,o.custody.walletAddress));await operations.assertEvmAccountAvailable(o.profileHash,1,o.custody.walletAddress);await assert.rejects(operations.resolvePrepare({kind:"relay_unsigned",profileHash:o.profileHash,operationId:o.operationId,idempotencyHash:o.idempotencyHash,requestHash:o.requestHash}));await assert.rejects(async()=>f.service.records.persist(merchantMove(o,"prepared",o.createdAt,{signingAttempts:1})));assert.equal(canonicalJson(await f.service.status(o.operationId)),canonicalJson(o));});
test("generic unrelated signed transaction cannot be used by finite custody",async t=>{const f=await setup(t),o=await f.prepare();await assert.rejects(verifyMerchantRaw(o,RAW_TRANSACTION));});
test("CLI and MCP discovery identify finite merchant with explicit same-proof delivery observer",()=>{assert.equal(bindArgv(["x402","merchant","observe","--operation","a".repeat(64),"--deliver"]).request.command,"x402.merchant.observe");assert.ok(MCP_TOOLS.some(t=>t.name.includes("merchant")&&t.name.includes("approve")));});

test("challenge drift during consent refuses before custody",async t=>{const f=await setup(t),o=await f.prepare();f.onApprove(async()=>{f.http.get=async()=>{const v=observation(new Date(o.createdAt));const c=structuredClone(challenge);c.accepts[0]!.amount="1";return {...v,rawHeaderPairs:[["payment-required",Buffer.from(JSON.stringify(c)).toString("base64")]]};};});await assert.rejects(f.service.approve(o.operationId));assert.equal(f.signs(),0);assert.equal(f.rpc.sends,0);});
test("owner alias collision refuses before any signature",async t=>{const f=await setup(t),o=await f.prepare();await f.state.writeWallet((await import("../../src/state.js")).sealWallet({schemaVersion:"apn.state.v1",profile:"alias",profileHash:f.state.profileHash("alias"),address:o.custody.walletAddress,createdAt:o.createdAt,bindingHash:"e".repeat(64)}));await assert.rejects(f.service.approve(o.operationId));assert.equal(f.signs(),0);assert.equal(f.rpc.sends,0);});
test("policy activation during paced dispatch blocks the actual POST after the permanent fence",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.queued=async()=>{await f.activate();};const held=await f.service.approve(o.operationId);assert.equal(held.state,"unknown_finality");assert.equal(held.submissionAttempts,1);assert.equal(f.rpc.sends,0);assert.equal(f.signs(),1);});
test("HTTP 200 invalid price schema remains paid with failure evidence",async t=>{const f=await setup(t),o=await f.prepare(),get=f.http.get.bind(f.http);f.http.get=async input=>input.paymentSignature===undefined?get(input):{...observation(new Date(o.createdAt),200),bodyBytes:Buffer.from('{"bitcoin":{"usd":"fake"}}')};const held=await f.service.approve(o.operationId);assert.equal(held.state,"delivery_unknown");assert.equal(held.receipt?.status,"success");assert.equal(held.deliveryAttempts.at(-1)?.httpStatus,200);assert.ok(held.deliveryAttempts.at(-1)?.bodyHash);assert.equal(held.deliveryAttempts.at(-1)?.result,undefined);});
test("confirmed revert has no merchant disclosure and reconciles proven zero token effect",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.receiptOverride=r=>{r.status="0x0";r.logs=[];};const done=await f.service.approve(o.operationId);assert.equal(done.state,"reverted");assert.equal(done.terminal,true);assert.equal(f.headers.length,0);assert.equal(done.receipt?.networkFeeWei,"200000");});
test("crash after durable delivery start can only retry the same original proof",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.lost=true;await f.service.approve(o.operationId);const paid=await f.service.observe(o.operationId),proof=merchantProof(paid.frozen,paid.txHash!);await f.service.records.persist(merchantMove(paid,"delivery_unknown",paid.createdAt,{deliveryAttempts:[{at:paid.createdAt,proofHash:hashObject(proof),outcome:"started"}]}));const done=await f.service.observe(o.operationId,true);assert.equal(done.state,"delivered");assert.equal(done.deliveryAttempts.length,4);assert.equal(f.headers[0],proof);assert.equal(f.rpc.sends,1);assert.equal(f.signs(),1);});

test("explicit false delivery flag stays observation-only in CLI and MCP",()=>{const cli=bindArgv(["x402","merchant","observe","--operation","a".repeat(64),"--deliver","false"]).request;assert.equal(cli.command==="x402.merchant.observe"&&cli.deliver,false);const tool=MCP_TOOLS.find(t=>t.name==="apn_x402_merchant_observe")!;const mcp=bindMcpInput(tool.command,{operation:"a".repeat(64),deliver:false}).request;assert.equal(mcp.command==="x402.merchant.observe"&&mcp.deliver,false);});

test("saved genuine merchant 402 selects the exact second USDm requirement",async()=>{const saved=JSON.parse(await readFile("tests/core/merchant-challenge-fixture.json","utf8")),o=observation(new Date(saved.observedAt));const checked=merchantChallenge({...o,rawHeaderPairs:[["PAYMENT-REQUIRED",saved.paymentRequired]]});assert.deepEqual(checked.accepted,saved.challenge.accepts[1]);assert.deepEqual(checked.challenge,saved.challenge);});
test("receipt fee above the frozen envelope cannot authorize merchant disclosure",async t=>{const f=await setup(t),o=await f.prepare();f.rpc.receiptOverride=r=>{r.effectiveGasPrice="0xffff";};const held=await f.service.approve(o.operationId);assert.equal(held.receipt,null);assert.equal(f.headers.length,0);});

test("challenge drift after sealing prevents the first broadcast and holds the single signature",async t=>{const f=await setup(t),o=await f.prepare(),get=f.http.get.bind(f.http);let reads=0;f.http.get=async input=>{if(input.paymentSignature===undefined&&++reads===3){const v=observation(new Date(o.createdAt)),c=structuredClone(challenge);c.accepts[0]!.amount="1";return {...v,rawHeaderPairs:[["payment-required",Buffer.from(JSON.stringify(c)).toString("base64")]]};}return get(input);};const held=await f.service.approve(o.operationId);assert.equal(held.state,"unknown_finality");assert.equal(held.signingAttempts,1);assert.equal(held.submissionAttempts,0);assert.equal(f.signs(),1);assert.equal(f.rpc.sends,0);assert.equal(f.headers.length,0);await assert.rejects(f.service.approve(o.operationId));});

test("trusted wire deadline gate runs after DNS and blocks transport before physical send",async()=>{const {BridgeHttps}=await import("../../src/lifi/https.js");let resolved=false;const transport=new BridgeHttps(async()=>{resolved=true;return [{address:"1.1.1.1",family:4}];});const sentinel=new Error("expired after DNS");await assert.rejects(transport.request("https://mainnet.megaeth.com/rpc","POST","{}",1024,"APN_RPC_CONFIG",()=>{assert.equal(resolved,true);throw sentinel;}),error=>error===sentinel);});
