import assert from "node:assert/strict";
import test from "node:test";
import { createAllowedCalldataTerms, createERC20TransferAmountTerms, createRedeemerTerms,
  createTimestampTerms, createValueLteTerms } from "@metamask/delegation-core";
import { ROOT_AUTHORITY, type PermissionContext } from "@metamask/smart-accounts-kit";
import { createx402DelegationProvider } from "@metamask/smart-accounts-kit/experimental";
import { SIGNABLE_DELEGATION_TYPED_DATA, decodeDelegations, encodeDelegations,
  toDelegationStruct } from "@metamask/smart-accounts-kit/utils";
import { keccak256, pad, toHex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { x402Erc7710Client } from "@metamask/x402";
import { canonicalJson, sha256 } from "../../src/canonical.js";
import { OfficialSmartAccountX402Engine } from "../../src/metamask-smart-account-x402.js";
import { smartAccountEnvironment } from "../../src/metamask-smart-account-grant.js";
import type { GrantedSmartAccountPermissionRecord } from "../../src/metamask-smart-account-record.js";
import type { Address, Hex } from "../../src/model.js";
import { OfficialErc7710Engine } from "../../src/smart-account-erc7710/engine.js";
import type { Erc7710MaterialIntent, Erc7710PaymentPayload } from "../../src/smart-account-erc7710/intent.js";
import { validateErc7710Material } from "../../src/smart-account-erc7710/validation.js";
import { saSalt } from "../../src/smart-account-gasless/integrity.js";
import { saRegistry } from "../../src/smart-account-gasless/registry.js";
import type { X402OperationRecord } from "../../src/x402-state-integrity.js";

const SESSION_KEY = `0x${"2".repeat(64)}` as Hex;
const SESSION = privateKeyToAccount(SESSION_KEY).address.toLowerCase() as Address;
const OWNER = privateKeyToAccount(`0x${"1".repeat(64)}` as Hex).address.toLowerCase() as Address;
const PAYEE = "0x3333333333333333333333333333333333333333" as Address;
const OPERATION = "4".repeat(64), FINGERPRINT = "5".repeat(64);
const AFTER = 1_788_393_600, BEFORE = AFTER + 300;
// Generated by the unrefactored OfficialSmartAccountX402Engine at commit d2bd3f89e117a87397c01677a821a77ab34d433d.
const PRE_REFACTOR_X402_SHA256 = "ebf6786c7892b3eb9096d8a6428050509f092aa2e5f28fdadc690c038d19b0df";

function rootContext(): Hex {
  return encodeDelegations([{ delegate: SESSION, delegator: OWNER, authority: ROOT_AUTHORITY,
    caveats: [], salt: "0x01", signature: `0x${"11".repeat(65)}` }]).toLowerCase() as Hex;
}

function intent(salt: Hex = saSalt(OPERATION, FINGERPRINT)): Erc7710MaterialIntent {
  const registry = saRegistry(8453);
  const requirements = { scheme: "exact", network: "eip155:8453", asset: registry.token.address,
    amount: "10000", payTo: PAYEE, maxTimeoutSeconds: 300,
    extra: { assetTransferMethod: "erc7710", facilitatorAddresses: registry.facilitatorAddresses } };
  return { operationId: OPERATION, fingerprint: FINGERPRINT, chainId: 8453, token: registry.token.address,
    amountAtomic: "10000", payee: PAYEE, ownerAddress: OWNER, sessionAddress: SESSION,
    delegationManager: registry.protocol.manager.address, afterUnix: AFTER, beforeUnix: BEFORE,
    facilitatorAddresses: registry.facilitatorAddresses, salt, requirements, rootContext: rootContext() };
}

test("real pinned SDK creates one deterministic direct child plus the exact root", async () => {
  const request = intent(), engine = new OfficialErc7710Engine();
  const first = await engine.create(request, { sessionPrivateKey: SESSION_KEY, rootContext: request.rootContext });
  const second = await engine.create(request, { sessionPrivateKey: SESSION_KEY, rootContext: request.rootContext });
  assert.deepEqual(first, second);
  assert.deepEqual(Object.keys(first).sort(), ["accepted", "payload", "x402Version"]);
  assert.deepEqual(Object.keys(first.payload).sort(), ["delegationManager", "delegator", "permissionContext"]);
  const chain = decodeDelegations(first.payload.permissionContext);
  assert.equal(chain.length, 2);
  assert.equal(encodeDelegations([chain[1]!]).toLowerCase(), request.rootContext);
  const validated = await validateErc7710Material(request, first);
  assert.equal(validated.permissionContext, first.payload.permissionContext.toLowerCase());
  assert.notEqual(saSalt(OPERATION, FINGERPRINT), keccak256(toHex(`apn.smart-account.x402\0${OPERATION}\0${FINGERPRINT}`)));
});

test("independent validation rejects direct shape, identity, root and caveat mutations", async () => {
  const request = intent(), payment = await new OfficialErc7710Engine().create(request,
    { sessionPrivateKey: SESSION_KEY, rootContext: request.rootContext });
  const chain = decodeDelegations(payment.payload.permissionContext);
  const cases: Erc7710PaymentPayload[] = [
    { ...payment, resource: { url: "https://seller.invalid" } } as unknown as Erc7710PaymentPayload,
    { ...payment, accepted: { ...payment.accepted, amount: "10001" } },
    { ...payment, payload: { ...payment.payload, delegator: PAYEE } },
    { ...payment, payload: { ...payment.payload, permissionContext: encodeDelegations([chain[0]!]) } },
    { ...payment, payload: { ...payment.payload, permissionContext: encodeDelegations([
      { ...chain[0]!, caveats: chain[0]!.caveats.slice(1) }, chain[1]!,
    ]) } },
  ];
  for (const candidate of cases) await assert.rejects(validateErc7710Material(request, candidate));
});

test("independent validation rejects re-signed recipient, amount, native, expiry, redeemer, args, authority and domain changes", async () => {
  const request = intent(), payment = await new OfficialErc7710Engine().create(request,
    { sessionPrivateKey: SESSION_KEY, rootContext: request.rootContext });
  const environment = smartAccountEnvironment(), wrong = "0x6666666666666666666666666666666666666666" as Address;
  const enforcer = (name: keyof typeof environment.caveatEnforcers) => environment.caveatEnforcers[name]!.toLowerCase();
  const replace = (name: keyof typeof environment.caveatEnforcers,
    update: (caveat: ReturnType<typeof decodeDelegations>[number]["caveats"][number]) =>
    ReturnType<typeof decodeDelegations>[number]["caveats"][number]) =>
    (child: ReturnType<typeof decodeDelegations>[number]) => ({ ...child, caveats: child.caveats.map(caveat =>
      caveat.enforcer.toLowerCase() === enforcer(name) ? update(caveat) : caveat) });
  const cases = [
    await resign(payment, replace("AllowedCalldataEnforcer", caveat => ({ ...caveat,
      terms: createAllowedCalldataTerms({ startIndex: 4, value: pad(wrong, { size: 32 }) }) }))),
    await resign(payment, replace("ERC20TransferAmountEnforcer", caveat => ({ ...caveat,
      terms: createERC20TransferAmountTerms({ tokenAddress: request.token, maxAmount: 10_001n }) }))),
    await resign(payment, replace("ValueLteEnforcer", caveat => ({ ...caveat,
      terms: createValueLteTerms({ maxValue: 1n }) }))),
    await resign(payment, replace("TimestampEnforcer", caveat => ({ ...caveat,
      terms: createTimestampTerms({ afterThreshold: request.afterUnix, beforeThreshold: request.beforeUnix + 1 }) }))),
    await resign(payment, replace("RedeemerEnforcer", caveat => ({ ...caveat,
      terms: createRedeemerTerms({ redeemers: [wrong] }) }))),
    await resign(payment, replace("ValueLteEnforcer", caveat => ({ ...caveat, args: "0x" }))),
    await resign(payment, child => ({ ...child, authority: `0x${"8".repeat(64)}` as Hex })),
    await resign(payment, child => child, { chainId: 1 }),
  ];
  for (const candidate of cases) await assert.rejects(validateErc7710Material(request, candidate));
});

test("legacy x402 matches the pre-refactor SDK engine and fixed historical bytes", async () => {
  const direct = intent(keccak256(toHex(`apn.smart-account.x402\0${OPERATION}\0${FINGERPRINT}`)));
  const record = { session_private_key: SESSION_KEY, session_address: SESSION, grant_context: direct.rootContext,
    owner_address: OWNER, delegation_manager: direct.delegationManager } as GrantedSmartAccountPermissionRecord;
  const resource = { url: "https://seller.example/item", description: "legacy", mimeType: "application/json" };
  const operation = { operationId: OPERATION, fingerprint: FINGERPRINT, wallet: OWNER, payee: PAYEE,
    amountAtomic: direct.amountAtomic, authorization: { createdAt: String(AFTER) },
    sellerWire: { resourceCanonicalJson: canonicalJson(resource) },
    selectedOffer: { declaredCanonicalJson: canonicalJson(direct.requirements), resolved: { assetTransferMethod: "erc7710" } },
    delegatedMaterial: { method: "erc7710", sessionAddress: SESSION, delegationManager: direct.delegationManager,
      effectiveExpiryUnix: String(BEFORE), facilitatorAddresses: direct.facilitatorAddresses } } as unknown as X402OperationRecord;
  const legacy = await new OfficialSmartAccountX402Engine().create({ record, operation,
    approvedFacilitators: direct.facilitatorAddresses });
  const historical = await preRefactorX402(direct, resource);
  const common = await new OfficialErc7710Engine().create(direct,
    { sessionPrivateKey: SESSION_KEY, rootContext: direct.rootContext });
  assert.deepEqual(legacy, historical);
  assert.deepEqual(legacy.payload, common.payload);
  assert.deepEqual(legacy.accepted, common.accepted);
  assert.deepEqual(legacy.resource, resource);
  assert.equal("extensions" in legacy, false);
  assert.equal(smartAccountEnvironment().DelegationManager.toLowerCase(), direct.delegationManager);
  assert.equal(sha256(canonicalJson(historical)), PRE_REFACTOR_X402_SHA256);
  assert.equal(sha256(canonicalJson(legacy)), PRE_REFACTOR_X402_SHA256);
});

async function preRefactorX402(request: Erc7710MaterialIntent,
  resource: { readonly url: string; readonly description: string; readonly mimeType: string }) {
  const provider = createx402DelegationProvider({ account: privateKeyToAccount(SESSION_KEY),
    environment: smartAccountEnvironment(), from: request.sessionAddress, salt: request.salt,
    parentPermissionContext: request.rootContext as PermissionContext,
    caveats: [{ type: "timestamp", afterThreshold: request.afterUnix, beforeThreshold: request.beforeUnix }],
    redeemers: { requireRedeemers: true, addresses: [...request.facilitatorAddresses] } });
  const created = await new x402Erc7710Client({ delegationProvider: provider })
    .createPaymentPayload(2, request.requirements);
  return { x402Version: 2 as const, resource, accepted: request.requirements, payload: created.payload };
}

async function resign(payment: Erc7710PaymentPayload,
  mutate: (child: ReturnType<typeof decodeDelegations>[number]) => ReturnType<typeof decodeDelegations>[number],
  domain: { readonly chainId: number; readonly verifyingContract?: Address } = { chainId: 8453 },
): Promise<Erc7710PaymentPayload> {
  const chain = decodeDelegations(payment.payload.permissionContext), unsigned = {
    ...mutate(chain[0]!), signature: "0x" as Hex,
  };
  const signature = await privateKeyToAccount(SESSION_KEY).signTypedData({
    domain: { chainId: domain.chainId, name: "DelegationManager", version: "1",
      verifyingContract: domain.verifyingContract ?? payment.payload.delegationManager },
    types: SIGNABLE_DELEGATION_TYPED_DATA,
    primaryType: "Delegation",
    message: toDelegationStruct(unsigned),
  });
  return { ...payment, payload: { ...payment.payload,
    permissionContext: encodeDelegations([{ ...unsigned, signature }, chain[1]!]) } };
}
