import type { SeiFundingService } from "./lifi/sei-gaszip-service.js";
import type { CircleEvmService } from "./circle-v2-evm/runtime.js";
import type { MegaFundingService } from "./lifi/mega-gaszip-service.js";
import type { RelayUnsignedPrepareService, RelayPreparePorts } from "./relay/prepare.js";
import type { RelayReadOnlyPreflightService, RelayPreflightPorts } from "./relay/preflight.js";
import type { RelayKeylessStatusService } from "./relay/status.js";
import type { RelayObserveService } from "./relay/observe.js";
import type { RelayBaseObserveService } from "./relay/base-observe.js";
import type { RelayArbitrumSourceObserveService } from "./relay/arbitrum-source-observe.js";
import type { RelayArbitrumApprovalDecisionService } from "./relay/arbitrum-approval-decision.js";
import type { RelayArbitrumApprovalExecuteService } from "./relay/arbitrum-approval-execute.js";
import type { RelayArbitrumDepositDispatchService } from "./relay/arbitrum-deposit-dispatch.js";
import type { WrappingSecretPort } from "./macos-keychain.js";
import type { ClockPort, HttpPort, IdPort, NativePort, RpcPort, WaitPort } from "./ports.js";
import type { ProfilePolicyApprovalPort } from "./policy-approval.js";
import type { ProfilePolicyPort } from "./profile-policy.js";
import type { HttpsBaseRpc } from "./rpc.js";
import type { TransferApprovalPort } from "./tty-approval.js";
import type { TtyTransferApprovalOptions } from "./tty-approval.js";
import type { ForegroundAuthenticationPort, ProviderProfileRepositoryPort, ProviderRegistryPort, X402PaymentMaterialPort } from "./provider-ports.js";
import type { ProviderX402TransactionEvidencePort } from "./provider-x402-transaction-port.js";
import type { ProviderAuthorizationStorePort } from "./encrypted-provider-authorization-store.js";
import type { SmartAccountPermissionStorePort } from "./encrypted-smart-account-permission-store.js";
import type { SessionKeyFactoryPort } from "./metamask-smart-account-adapter.js";
import type { SmartAccountConsentPort } from "./metamask-smart-account-consent.js";
import type { ChainWalletStoragePort, DirectRailPort, RailApprovalPort } from "./direct-rail-ports.js";
import type { ChainPolicyApprovalPort } from "./chain-policy.js";
import type { BridgeDependencies } from "./lifi/service.js";
import type { CircleV2ApprovalExecutor as CircleApprovalService } from "./lifi/circle-v2-approval-executor.js";
import type { OneClickSourceService } from "./lifi/near-oneclick-source-service.js";
import type { CircleV2SourceService } from "./lifi/circle-v2-source-service.js";
import type { GaslessDependencies } from "./gasless/service.js";
import type { GaslessUsdtOperationService } from "./gasless-usdt/service.js";
import type { GaslessUsdtCommandPrepare, UsdtCommandPrepareOptions } from "./gasless-usdt/command-prepare.js";
import type { GaslessUsdtCommandExecute, UsdtCommandExecuteOptions } from "./gasless-usdt/command-execute.js";
import type { MetaMaskGaslessDependencies } from "./metamask-gasless/service.js";
import type { OperationAbandonApprovalPort } from "./operation-abandon-approval.js";
import type { SmartAccountGaslessDependencies } from "./smart-account-gasless/service.js";
import type { FacilitatorGaslessDependencies } from "./facilitator-gasless/service.js";
import type { UniswapGuardedSwapBuilder } from "./swap/uniswap-service.js";
import type { SunSwapReadOnlyQuoteBuilder } from "./swap/sunswap-tron/command-service.js";
import type { JupiterReadOnlyQuoteBuilder } from "./swap/jupiter-solana/command-service.js";
import type { PortfolioDependencies } from "./portfolio/command.js";
import type { AllowlistPolicyApprovalPort } from "./allowlist-policy-activation.js";
import type { CommandRequest } from "./commands.js";
import type { GuardedSwapPolicyResolver, GuardedSwapRuntime } from "./swap/runtime.js";
import type { UniswapTokenCommandRuntime } from "./swap/uniswap-v3/token-execution.js";
import type { OrcaProgramPinVerifier } from "./swap/orca-solana/pins.js";
import type { OrcaStableConsentPort } from "./swap/orca-solana/stable-approval.js";
import type { Permit2PreflightPorts } from "./x402-permit2/preflight.js";
import type { OrcaKeylessQuoteRequest } from "./swap/orca-solana/builder.js";
import type { StargateNativeService } from "./stargate-v2/native-runtime.js";
import type { StargateTokenService } from "./stargate-v2/token-runtime.js";

export interface RuntimeFactoryOptions {
  /** Synthetic read-only preflight seam; production uses the bounded HTTPS source. */
  readonly permit2PreflightPorts?: Permit2PreflightPorts;
  /** Synthetic CLI test seam; source runtime still owns confirmation, pacing, and source effect guards. */
  readonly relayExecuteTransport?: Pick<HttpsBaseRpc, "batchCall" | "submitRawTransaction">;
  readonly relayExecuteTtyOptions?: TtyTransferApprovalOptions;
  readonly relayPrepare?: RelayUnsignedPrepareService;
  readonly relayPreparePorts?: RelayPreparePorts;
  readonly relayPreflight?: RelayReadOnlyPreflightService;
  readonly relayPreflightPorts?: RelayPreflightPorts;
  readonly relayStatus?: RelayKeylessStatusService;
  readonly relayStatusFetch?: typeof fetch;
  readonly relayObserve?: RelayObserveService;
  readonly relayBaseObserve?: RelayBaseObserveService;
  readonly relayArbitrumObserve?: RelayArbitrumSourceObserveService;
  readonly relayArbitrumObserveRpc?: HttpsBaseRpc;
  readonly relayArbitrumApprovalDecision?: RelayArbitrumApprovalDecisionService;
  readonly relayArbitrumApprovalExecute?: RelayArbitrumApprovalExecuteService;
  readonly relayArbitrumDepositDispatch?: RelayArbitrumDepositDispatchService;
  readonly relayArbitrumApprovalRpc?: Pick<HttpsBaseRpc, "batchCall">;
  readonly relayArbitrumApprovalExecuteRpc?: Pick<HttpsBaseRpc, "batchCall" | "submitRawTransaction">;
  readonly relayArbitrumDepositDispatchRpc?: Pick<HttpsBaseRpc, "batchCall" | "submitRawTransaction">;
  readonly relayObserveBaseRpc?: HttpsBaseRpc;
  readonly relayObserveSourceRpc?: HttpsBaseRpc;
  readonly relayObserveBnbRpc?: HttpsBaseRpc;
  readonly stargateNative?: StargateNativeService;
  readonly circleEvm?: CircleEvmService;
  readonly stargateToken?: StargateTokenService;
  readonly portfolio?: PortfolioDependencies;
  readonly uniswapRuntime?: GuardedSwapRuntime<Extract<CommandRequest, { readonly command: "swap.uniswap.quote" }>>;
  readonly uniswapTokenRuntime?: UniswapTokenCommandRuntime;
  readonly sunswapRuntime?: GuardedSwapRuntime<Extract<CommandRequest, { readonly command: "swap.sunswap.quote" }>>;
  readonly orcaRuntime?: GuardedSwapRuntime<OrcaKeylessQuoteRequest>;
  readonly uniswap?: UniswapGuardedSwapBuilder;
  /** Test seam for the owner's active sealed swap policy. Production reads the activated allowlist revision. */
  readonly swapPolicy?: GuardedSwapPolicyResolver;
  readonly sunswap?: SunSwapReadOnlyQuoteBuilder;
  readonly jupiter?: JupiterReadOnlyQuoteBuilder;
  readonly facilitatorGasless?: FacilitatorGaslessDependencies;
  readonly smartAccountGasless?: SmartAccountGaslessDependencies;
  readonly metaMaskGasless?: MetaMaskGaslessDependencies;
  readonly gasless?: GaslessDependencies;
  readonly gaslessUsdt?: GaslessUsdtOperationService;
  readonly gaslessUsdtPrepare?: GaslessUsdtCommandPrepare;
  readonly gaslessUsdtPrepareOptions?: UsdtCommandPrepareOptions;
  readonly gaslessUsdtExecute?: GaslessUsdtCommandExecute;
  readonly gaslessUsdtExecuteOptions?: UsdtCommandExecuteOptions;
  readonly bridge?: BridgeDependencies;
  readonly circleApproval?: CircleApprovalService;
  readonly circleSource?: CircleV2SourceService;
  readonly oneClickSource?: OneClickSourceService;
  readonly seiFunding?: SeiFundingService;
  readonly megaFunding?: MegaFundingService;
  readonly chainAccounts?: ChainWalletStoragePort;
  readonly directRails?: readonly DirectRailPort[];
  readonly railApproval?: RailApprovalPort;
  readonly chainPolicyApproval?: ChainPolicyApprovalPort;
  readonly allowlistPolicyApproval?: AllowlistPolicyApprovalPort;
  readonly solanaRpcUrl?: string;
  /** Offline transport injection; production uses the guarded Solana HTTPS fetch. */
  readonly solanaRpcFetch?: typeof fetch;
  readonly solanaRpcNow?: () => number;
  readonly solanaRpcWait?: (milliseconds: number) => Promise<void>;
  /** Offline acceptance only; the CLI exposes no option to replace pinned program proof. */
  readonly orcaStablePinVerifier?: OrcaProgramPinVerifier;
  /** Offline acceptance only; production reads exact consent from the owner TTY. */
  readonly orcaStableExecuteConsent?: OrcaStableConsentPort;
  /** Offline acceptance only; production reads separate recovery consent from the owner TTY. */
  readonly orcaStableRecoveryConsent?: OrcaStableConsentPort;
  readonly tronRpcUrl?: string;
  readonly stateRoot?: string;
  readonly native?: NativePort;
  readonly wrappingSecret?: WrappingSecretPort;
  readonly approval?: TransferApprovalPort;
  readonly policy?: ProfilePolicyPort;
  readonly policyApproval?: ProfilePolicyApprovalPort;
  readonly rpc?: RpcPort;
  readonly http?: HttpPort;
  readonly clock?: ClockPort;
  readonly ids?: IdPort;
  readonly wait?: WaitPort;
  readonly profileRepository?: ProviderProfileRepositoryPort;
  readonly providerRegistry?: ProviderRegistryPort;
  readonly foregroundAuthentication?: ForegroundAuthenticationPort;
  readonly providerTransactionEvidence?: ProviderX402TransactionEvidencePort;
  readonly providerAuthorizationStore?: ProviderAuthorizationStorePort;
  readonly smartAccountPermissionStore?: SmartAccountPermissionStorePort;
  readonly smartAccountConsent?: SmartAccountConsentPort;
  readonly smartAccountSessionKeys?: SessionKeyFactoryPort;
  readonly smartAccountX402Material?: X402PaymentMaterialPort;
  readonly operationAbandonApproval?: OperationAbandonApprovalPort;
}
